### ISSUE TITLE
Death Knight perma ghoul - Leap is on pet GCD

### ISSUE THREAD

**Issue by dariuzsdk** [JamminL/wotlk-classic-bugs#102]
#### Death Knight ghoul "Leap" spell puts pet on GCD
{Describe how that mechanic/spell/npc is currently working, in detail}
Currently, when you use leap it puts the pet on GCD
          {Describe the steps to reproduce the particular bug, in detail:
        1. Use Leap
  #### 1.3  Source Material
[{Video, Posts, etc..}](https://www.twitch.tv/videos/1520500641)
#### Should not on pet's GCD
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
[{Video, Posts, etc..}](https://youtu.be/paskamMBWZ0?t=560)

**Comment by watchyoursixx** [comment]
This was just a visual bug. You can see it "starts" to show GCD, but then doesn't show the full circle in the linked timestamped video. However, if it was truly not on GCD, there would be no swipe at all, like when you use "huddle".

Later in that same video, it's working properly and leap is clearly on GCD.
https://youtu.be/paskamMBWZ0?t=889

**Comment by watchyoursixx** [comment]
https://youtu.be/BYK6OkFwbv8?t=271
For more "clear" proof since the other vid looked kinda sus after reviewing more, likely because of the macroed casts instead of auto cast
You can see gcd ends, ghoul leaps, and puts other spells on GCD

I actually think I found another bug though, since it shows that ghoul all abilities are on GCD, whereas on the beta Huddle is not on the GCD
