### ISSUE TITLE
[BUG] Friendly names not showing in arena

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#215]
#### 1.1. Description
If you don't target your party member, their names won't be shown
  #### 1.2. How to Reproduce
           1. Queue arena with someone
           2. Go close to them
           3. Check that their name and guild only shows once you target them
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/107503518/181253789-16c65d67-815a-42bb-9bbd-f5261b5ecbf6.png)
#### 2.1. Description
With the UI setting on, friendly names should be visible
  #### 2.2 Source Material
Not necessary

**Comment by Evolvee** [comment]
There is another issue with names thats actually in place ever since classic TBC beta - you cannot see friendly names if they are stealthed. So what can often happen is that you can mistake your own rogue or druid for the enemy one when you need to act in a split second.

This can be hackfixed through UI modifications (addon) but shouldnt have to be.
