### ISSUE TITLE
[BUG] Shield Block / Shield Wall / Shield Reflection bug

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#222]
#### 1.1. Description
If you use one of these spells, and go back to 2-Hand, you still have the buff (and the effect still works)
  #### 1.2. How to Reproduce
           1. Go in 1-hand and shield
           2. Press one of these 3 spells
           3. Go back to 2-hand
  #### 1.3  Source Material
Not yet
#### 2.1. Description
If you go back to 2-hand, you should lose Shield Block / Shield Wall / Shield Buff
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
This is NAB for fury warriors with titan grip, but it is a **bug** for every other case. 

There's multiple evidence that shows arms warriors swapping weapons and stances and the buff disappearing. This was also documented on multiple forum posts:

[- Video of ARMS warrior losing shield wall after swapping weapons and stance](https://www.youtube.com/watch?v=EwLOcI4h_kg&t=1624s)
[- Video of Arms warrior losing shield wall after swapping weapons and stance #2](https://youtu.be/EwLOcI4h_kg?t=1064) 
[- Post mentioning the exploit working for fury warriors only](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/218239-shield-wall-2h-weps.html)

[- Fury warrior video explaining the bug, and multiple comments agreeing Fury only (because of titan's grip)](https://www.youtube.com/watch?v=H4K8puGa1vs)
[- Another Fury warrior example of keeping the shieldwall buff after weapon and stance swap](https://www.youtube.com/watch?t=72&v=OqCk2_QkOio&feature=youtu.be)

**Comment by Shintaxgg** [comment]
It's only when warrior remove his shield that make the buff disappearing, changing stance doesn't do anything, you can wall and go battle stance or berserker stance and keep your wall, reflect, block

**Comment by MuffledBaneMask** [comment]
Also affects Holy Shield, and others. 
Vanilla 1.12 (and below) behavior is actually the opposite of Wrath, and you're able to retain the buffs in legacy Vanilla after taking off your shield, but not in Wrath. Wrath should be removing all auras that come from spells with item requirements whenever those items are no longer equipped.

**Comment by JamminL** [comment]
> Also affects Holy Shield, and others. Vanilla 1.12 (and below) behavior is actually the opposite of Wrath, and you're able to retain the buffs in legacy Vanilla after taking off your shield, but not in Wrath. Wrath should be removing all auras that come from spells with item requirements whenever those items are no longer equipped.

Yeap! The only correction here is that in wotlk it checks for whether the slot is equiped, not the item. As evidenced by warriors with dual wield being able to keep shieldwall after swapping the shield for another weapon

**Comment by Shintaxgg** [comment]
Still isn't fixed as of new build

**Comment by Shintaxgg** [comment]
fixed
