### ISSUE TITLE
[#SomeChanges Suggestion] Add the tinnitus debuff to Drums of Speed

### ISSUE THREAD

**Issue by dombi676** [JamminL/wotlk-classic-bugs#233]
### Description
In original WotLK [Drums of Speed](https://www.wowhead.com/wotlk/item=29530/drums-of-speed) did not incur the tinnitus debuff when used, allowing a party of 4 leatherworkers to have 100% uptime of a 15% movement speed buff. 
Adding the tinnitus debuff would be consistent with the changes done to TBC drums for the same reason, avoiding degenerate gameplay of having 20 leatherworkers in a raid to get 100% uptime on the movement speed buff.

![image](https://user-images.githubusercontent.com/37704269/181916746-c5d10421-db92-4412-8e2a-53652bf2791d.png)

**Comment by simonizeshow** [comment]
I second this as a good # somechanges suggestion.

**Comment by Teebown** [comment]
Greater drums currently give tinnitus but normal drums of speed don't appear to trigger the debuff according to wowhead.

![definitely_gives_tinnitus](https://user-images.githubusercontent.com/108202746/183289606-828e73a3-189c-4aa1-ab5e-873f79d8feee.png)
![Screenshot_20220807-065607_Discord](https://user-images.githubusercontent.com/108202746/183289612-b9ba9df1-f392-4225-bb9b-238c5728c027.jpg)
![Screenshot_20220807-065933_Chrome](https://user-images.githubusercontent.com/108202746/183289614-6aaed476-58fc-43ac-bd3a-df25ef4e298f.jpg)
![Screenshot_20220807-070000_Chrome](https://user-images.githubusercontent.com/108202746/183289615-f1ff0a57-44b4-4cf1-8ff5-2612d3b8550e.jpg)

**Comment by iamjackthelad** [comment]
I've been testing this on beta and it seems ridiculously broken.

Unlike many (all?) other speed increases, the speed increase on drums stacks (_multiplicatively_) with others.

Aspect of the Pack + Drums of Speed = 150% movespeed, with Drums giving 19.5% instead of 15%.
Swiftness of Zanza + Drums of Speed = 138% movespeed, with Drums giving 18% instead of 15%.
Boots enchants + Drums of Speed = 124% movespeed, with Drums giving 16% instead of 15%.

This will be "mandatory" for speedrunning raids in particular and it seems super degenerate and unfun. It's also directly counter to Blizzard's previous changes to drums which were intended to make them be or feel "less mandatory".

Really hope this gets fixed before launch and we don't see 20 leatherworkers getting every world first.

**Comment by pleasefixdrumsofspeed** [comment]
Please for the love of god fix this before launch!!
