### ISSUE TITLE
[BUG] Resilience Visual Client Bug

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#238]
#### 1.1. Description
Resilience shows TBC values on the client character sheet instead of the actual, wotlk values. This is visual only, resilience is working as intended
  #### 1.2. How to Reproduce
           1. Equip a resil trinket
           2. Check how the damage reduction isn't doubled to match wrath standards
  #### 1.3  Source Material
Not yet
#### 2.1. Description
Resilience values on character sheet should match wotlk values
  #### 2.2 Source Material
World of Warcraft Hotfix (2010-01-20): Resilience damage reduction doubled. So depending on their current amount of resilience, characters might experience a 10 to 20% decrease in damage taken from other players
https://wowwiki-archive.fandom.com/wiki/Resilience

**Comment by McPero** [comment]
3.0.3 patch 82 resil ([source](https://www.engadget.com/2008-12-25-wrath-101-resilience-at-level-80.html)) is required to get 1% reduction in first category (reduction to crit chance against you). In addition that 1% turns into 2.2% for 2nd category (drain and crit damage reduction) instead of 2% which was the case in TBC ([source](https://wowwiki-archive.fandom.com/wiki/Resilience)).

3.2.0 patch DoT damage reduction was removed and replaced with overall damage reduction (3rd category). In addition you needed 15% more resilience to achieve same % reductions as before. This means now you needed 82 * 1.15 = 94.3 points of resilience for 1% of reduction in 1st category and 94.3/2.2=42.864 in 2nd category ([source](https://wowwiki-archive.fandom.com/wiki/Resilience)). What coefficient overall damage reduction was using is unclear but we can assume it was same as first category. 

Later hotfix says resilience damage reduction has been doubled, this means only 3rd category was doubled. 

Lets assume we have 943 resilience. Currently on beta tooltip will say this:
"
Resilience 943
Reduces chance to be critically hit by 10,00%.
Reduces the effect of mana-drains and the damage of critical strikes by 20,00%.
Provides 10,00% additional damage reduction against all damage done by player and their pets or minions.
"
What tooltip should say:
"
Resilience 943
Reduces chance to be critically hit by 10,00%.
Reduces the effect of mana-drains and the damage of critical strikes by 22,00%.
Provides 20,00% additional damage reduction against all damage done by player and their pets or minions.
"

I also believe testing should be done on actually behavior if the damage reductions are correct.

**Comment by JamminL** [comment]
Fixed as of build 3.4.0.45264
