### ISSUE TITLE
[BUG] Rogue Energy Generation is effected by Haste Rating

### ISSUE THREAD

**Issue by simonizeshow** [JamminL/wotlk-classic-bugs#248]
### 1. Current Behavior
With the update on 8/3, rogue energy is now effected by haste rating.
  #### 1.1. Description
  I have used a WeakAura to track the time it takes my character to generate 60 energy. It offers vastly different numbers when I am under the effects of Potion of Speed vs not, or when I equip a lot of passive haste gear vs very little passive haste gear.
  
  Example times without Potion of Speed active (seconds to generate 60 energy):
4.170
4.234
4.502
4.367
4.417
4.203
4.303
4.505
4.467
4.417

Example times with Potion of Speed active: 
3.604
3.696
3.791
3.738
3.754
3.849
3.873
3.802
3.809
3.829

From careful observation of the energy bar, I see two things happening. The first is the regular and expected smooth energy generation. The second is a "tick" of energy generation happening about every 2 seconds where my energy jumps up.

I think the timing of the "tick" relative to when I initiate my timer for measuring energy generation via the weakaura may explain the variation in observed times, or perhaps that is just related to server latency.

I would call this a CRITICAL BUG but I dont think I'm allowed to make that designation. It completely breaks the rogue class making it way way too powerful, not to mention just not being correct behavior.

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Lower your energy
           2. Wait
           3. Measure the time it takes to regenerate 60 energy
           4. Modify your character's haste rating, then repeat 1-3.
  #### 1.3  Source Material
I could post a screenshot of the numbers I got from the WA but that doesn't seem helpful.
#### 2.1. Description
Haste should not be modifying your energy generation in Wrath of the Lich King.
  #### 2.2 Source Material
This was definitely not in Wrath. I'm not sure what expansion it got added in, but I didn't play that one.

**Comment by JamminL** [comment]
![image](https://user-images.githubusercontent.com/107503518/182745050-55dfe1b6-512b-4a71-9113-4606f019772c.png) this was a mechanic added in cata prepatch

**Comment by Aggrend** [comment]
Fix already checked in for this. Assuming it passes QA muster this should be resolved in the 8/10 update.

**Comment by where-fore** [comment]
There is still a remaining bug in energy generation for Rogues.

While under the effects of an energy regen percentage buff, such as Overkill, Vitality, or Adrenaline Rush, you will notice that on top of the extra energy regeneration there are some strange extra energy ticks - what Simonize noted as the "ticks". Through the use of [this weakaura](https://wago.io/flpHai0L9), you can find many different combinations of strange behaviour. [Here is a selection of tests I ran in a spreadsheet.](https://docs.google.com/spreadsheets/d/1DyvXau0AXhSnVkOGFj-7-rRF6fUPTcPAB5e-OYIpF9Y/edit?usp=sharing)

With just Overkill: Some tests resulted in expected energy regen (approx. 1 energy every 0.1s, and 2 energy every third 0.1s), as well as an extra 8-10 energy tick every 2.02 seconds - just like the ticks back in TBC and Classic. Some tests weren't quite as perfect to my eye, but maybe I just couldn't see the pattern.

With just Vitality: Same as Overkill (but with the expected pattern from 25% extra energy instead of Overkill's 30%)

With just Adrenaline Rush: The same energy ticks like Overkill, except they are significantly higher, having seen a tick as high as 34. Also secondarily, when spending energy on Backstab in these tests, I lost much less energy than expected (or gained a refuned at the same time) - sometimes on spending as little as 20 energy to cast a Backstab, and then getting an extra energy tick later, all while getting 2 energy every 0.1 second.

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
