### ISSUE TITLE
[#SomeChanges Suggestion] Hunter Swing Timers 

### ISSUE THREAD

**Issue by TheDunds** [JamminL/wotlk-classic-bugs#258]
Unlink Hunter ranged and melee swing timers 

Since it has been found out that linked swing timers match the reference client and no video proof has been found after many hours of research to say that linked swing timers are not in a bugged state. 

Id like to recommend a some changes to unlink the swing timers to match the way we have been playing hunter in tbc with the added addition of melee weaving, to further push the dps output, skill challenge and enjoyment in playing hunter in a variety of different situations. 

I understand there is also a glyph for hunter pvp for raptor strike to reduced incoming damage after a raptor strike, having to wait the full swing timer to get the raptor strike off in pvp doesn't sound right to me for the very fast paced action of pvp.

[trickdaemon](https://github.com/trickdaemon) commented [5 days ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1205921996)
+1, was a big fan of the feral and ret changes for tbc and this goes a long way for people that enjoy the playstyle like I do. Personally it's the only reason I keep playing my hunter, named Waeve; Back at level 60 melee weaving was a big joke compared to what it is in TBC and yet I still did it all the way back then because I find it really fun and engaging.

If nothing else, maybe Raptor Strike should be an instant strike untied to melee swing?

Thanks for your time!

[phbolduc](https://github.com/phbolduc) commented [4 days ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1206038811)
This is a great suggestion.

Melee weaving has been a really fun and engaging playstyle and most hunters would love to have it as an option in wotlk too.

[Ramose419](https://github.com/Ramose419) commented [4 days ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1206069026)
Melee Weaving has been the most enjoyable part of hunter for me for a while, The potential of it in wrath as a fast paced skilled gameplay loop is very compelling as well as filling a role of hybrid Ranged/Melee DPS that the game just simply does not have otherwise. some ways to preserve the playstyle if the timers truely cant be linked would be to take Mongoose bite off the GCD and make raptor strike an instant melee like someone above me said adding another layer to the rotation

[Yangxa380](https://github.com/Yangxa380) commented [4 days ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1206210095)
As my fellow hunters above me has stated, melee weaving is the best part about playing hunter. It is very sad too see that weaving might not be a thing anymore when wrath pre-patch goes live. So for the enjoyment for us hunters who enjoy weaving, please seperate the swing timers so we may keep weave through wrath aswell. Since there has already been some changes for other classes too make them more fun and engaging, me personally only feel that is right that hunters get #somechanges aswell.

Tight strings, sharp blades and happy hunting my fellow hunters!

#Makeweavinggreatagain

[Wicked73](https://github.com/Wicked73) commented [4 days ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1207037899) • 
Hunter has always felt like a clunky class to play, whether it be a mob running completely over your trap and not proccing it, or when you feign death and a mob still comes up to you and hits you a second later. Melee weaving is the complete opposite. Melee weaving allows for such fluid gameplay as a hunter, and by having melee and ranged swing timers linked its simply regressing the class to a more clunky style of gameplay. The linked swing timers effects more than just a dps increase in raid with melee weaving. For example when you're questing in the world and you pull a mob off your pet, walks into your melee range, has 3% health and boom you finish it off with a raptor strike. Can't do that anymore, now you have to wait 3 seconds for your melee swing. Or as Dund mentioned above, the raptor strike glyph for PvP becomes quite ineffective if we have to wait 3 seconds to mitigate damage. The bulk of damage has probably already happened in that 3 seconds, making that glyph essentially useless. That's just not fun. That makes me not want to play the class. I hope at the least a dialogue can be opened about the unlinking of swing timers, because it is much more than just melee weaving in raids. The changes to paladin seal twisting and feral power-shifting (and energy ticks) definitely holds the precedent to allow for hunters to experience similar treatment. #somechanges

[xOmenzerOx](https://github.com/xOmenzerOx) commented [4 days ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1207124165)
Swing timers really need to be un-linked. Melee-weaving really saved the class for me and made it so much fun to play. Not just in TBC, but since MC and BWL back in classic vanilla as well. It made the class literally have the most dynamic and interactive play style of anything I have played to date in classic and tbc. I cannot express how it feels to weave really well on a fight and the sense of accomplishment that comes along with it.

It is a real shame that macro users have tarnished the reputation of melee-weaving in general. There are many legit weavers who have been very enthusiastic about it since classic. I really hope that Blizzard can recognize this and find a different way to punish the ToS breakers and let weaving continue to happen. By not un-linking swing timers, all you accomplish is ruining fun for an enthusiastic and dedicated portion of your hunter player-base.

I really hope someone in the dev team reads this thread and takes some actions on the side of letting fun happen.

#SomeChanges

[Caelin360](https://github.com/Caelin360) commented [21 hours ago](https://github.com/JamminL/wotlk-classic-bugs/issues/258#issuecomment-1208444630)
Melee weaving is the most fun and engaging gameplay I have experienced in WoW. Paying close attention to character movement during raid, changing strategies and thinking about how to optimize melee uptime, practicing the rotation in my free time. I’ve never been more engaged in the game than when i’m weaving. Melee weave is the entire reason I enjoy playing Hunter.

Without this change, Raptor Strike is a dead ability in both PvE and PvP, and has no use in any practical situation.

Please consider unlinking the melee and range swing timers Blizzard.

#SomeChanges

**Comment by trickdaemon** [comment]
+1, was a big fan of the feral and ret changes for tbc and this goes a long way for people that enjoy the playstyle like I do. Personally it's the only reason I keep playing my hunter, named Waeve; Back at level 60 melee weaving was a big joke compared to what it is in TBC and yet I still did it all the way back then because I find it really fun and engaging. 

If nothing else, maybe Raptor Strike should be an instant strike untied to melee swing? 

Thanks for your time!

**Comment by phbolduc** [comment]
This is a great suggestion.

Melee weaving has been a really fun and engaging playstyle and most hunters would love to have it as an option in wotlk too.

**Comment by Ramose419** [comment]
Melee Weaving has been the most enjoyable part of hunter for me for a while, The potential of it in wrath as a fast paced skilled gameplay loop is very compelling as well as filling a role of hybrid Ranged/Melee DPS that the game just simply does not have otherwise. some ways to preserve the playstyle if the timers truely cant be linked would be to take Mongoose bite off the GCD and make raptor strike an instant melee like someone above me said adding another layer to the rotation

**Comment by Yangxa380** [comment]
As my fellow hunters above me has stated, melee weaving is the best part about playing hunter. It is very sad too see that weaving might not be a thing anymore when wrath pre-patch goes live. So for the enjoyment for us hunters who enjoy weaving, please seperate the swing timers so we may keep weave through wrath aswell. Since there has already been some changes for other classes too make them more fun and engaging, me personally only feel that is right that hunters get #somechanges aswell.

Tight strings, sharp blades and happy hunting my fellow hunters!

#Makeweavinggreatagain

**Comment by Wicked73** [comment]
Hunter has always felt like a clunky class to play, whether it be a mob running completely over your trap and not proccing it, or when you feign death and a mob still comes up to you and hits you a second later. Melee weaving is the complete opposite. Melee weaving allows for such fluid gameplay as a hunter, and by having melee and ranged swing timers linked its simply regressing the class to a more clunky style of gameplay. The linked swing timers effects more than just a dps increase in raid with melee weaving. For example when you're questing in the world and you pull a mob off your pet, walks into your melee range, has 3% health and boom you finish it off with a raptor strike. Can't do that anymore, now you have to wait 3 seconds for your melee swing. Or as Dund mentioned above, the raptor strike glyph for PvP becomes quite ineffective if we have to wait 3 seconds to mitigate damage. The bulk of damage has probably already happened in that 3 seconds, making that glyph essentially useless. That's just not fun. That makes me not want to play the class. I hope at the least a dialogue can be opened about the unlinking of swing timers, because it is much more than just melee weaving in raids.

**Comment by xOmenzerOx** [comment]
Swing timers really need to be un-linked. Melee-weaving really saved the class for me and made it so much fun to play. Not just in TBC, but since MC and BWL back in classic vanilla as well. It made the class literally have the most dynamic and interactive play style of anything I have played to date in classic and tbc. I cannot express how it feels to weave really well on a fight and the sense of accomplishment that comes along with it.

It is a real shame that macro users have tarnished the reputation of melee-weaving in general. There are many legit weavers who have been very enthusiastic about it since classic. I really hope that Blizzard can recognize this and find a different way to punish the ToS breakers and let weaving continue to happen. By not un-linking swing timers, all you accomplish is ruining fun for an enthusiastic and dedicated portion of your hunter player-base.

I really hope someone in the dev team reads this thread and takes some actions on the side of letting fun happen.

#SomeChanges

**Comment by Caelin360** [comment]
Melee weaving is the most fun and engaging gameplay I have experienced in WoW. Paying close attention to character movement during raid, changing strategies and thinking about how to optimize melee uptime, practicing the rotation in my free time. I’ve never been more engaged in the game than when i’m weaving. Melee weave is the entire reason I enjoy playing Hunter.

Without this change, Raptor Strike is a dead ability in both PvE and PvP, and has no use in any practical situation.

Please consider unlinking the melee and range swing timers Blizzard.

#SomeChanges

**Comment by yurpcraft** [comment]
Cleaning up this ticket.  In the future, please just thumbs up the post instead of a comment agreement to help cut throught the noise.

**Comment by watchyoursixx** [comment]
https://us.forums.blizzard.com/en/wow/t/fix-hunter-autoshot-to-melee-bug/1289726/28
per Aggrend's comments of the design intention from 2008 to make them linked, and their current behavior I'm going ahead and closing this one out as not planned.

I spoke with Aggrend later and there's a possibility they'll consider it in the future but as of now there is no plan to adjust the timers at all to be unlinked.
