### ISSUE TITLE
[BUG] Devouring Plague not healing

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#267]
*Issue submitted automatically through Google Forms by: gekku*<br/> 
 ### 1. Current Behavior <br/> 
 #### 1.1. Description <br/> 
Devouring Plague doesn't heal for 15% of the damage it's causing<br/> 
 #### 1.2. How to Reproduce <br/> 
  Drop some of your HP
Cast Devouring Plague on a Dummy
Notice it doesn't heal the caster when it damages <br/>
 #### 1.3  Source Material <br/> 
 _<br/> 
 ### 2. Expected Behavior<br/> 
  #### 2.1. Description <br/> 
Devouring Plague should heal the caster for 15% of it's damage every tick, as mentionned in the spell tooltip<br/> 
 #### 2.2 Source Material <br/> 
_

**Comment by rafalss** [comment]
It works fine against normal mobs. 

![spriest heals](https://user-images.githubusercontent.com/110211934/183266852-d418a5c2-874f-446c-846a-c38b2281be3c.png)

Seems to be only a case for Target Dummies, something I've already observed on Lock with Corruption and Drain Life. I would assume it's because in the combat log you always do 1 damage to dummies and the rest is overkill. The Corruption ticks still heal me for 1 damage from dummies.

![dummy](https://user-images.githubusercontent.com/110211934/183266863-b6585f3d-214c-41a2-ba16-ba03d86d7ace.png)
