### ISSUE TITLE
[#SomeChanges Suggestion] Nitro boost in arena

### ISSUE THREAD

**Issue by Oliaxz** [JamminL/wotlk-classic-bugs#359]
### Description
In a recent interview, it seems confirmed that nitro boost enchant will work for s5 and possibly longer. I just cant believe it and i have no word to express my disapointment. This forces everyone into picking engin for s5 and will make the game much more miserable to play. We will all suffer from this nitro plague. 

If they go through with this, then i guess we can forget about all the other suggested changes since it means that they catter to the people that dont take arena seriously, so the people that disrespect it and see it as a mini game.

Dont allow it out of respect for the people that actually care for arena, please?

**Comment by Evolvee** [comment]
Imagine disabling skull of impending doom, eng trap trinket, eng belt and bunch of other cheese shit just to enable rocket boots 4 seasons later, on **purpose**.

Feels like the decisions are coming from a bunch of ppl in which some of them want to preserve the competitivness of the arena while others are the usual 1490 rated BatChest casual-enjoyers, who unfortunately have a major say.

On one hand, they removed teams, implemented multiple QoL suggestions specifically for arenas, reduced RNG by allowing overcapped hit to penetrate miss auras once again, and then on the other hand they re-introduce elements that were removed from the game entirely __(for a good reason)_ such as rng tornadoes that follow no set path and spawn randomly without any warning, RoV fires _(tbh RoV is a complete troll even without the fires)_ and rocket boots... Its like 1 step forward, 2 steps backwards.

Over the last 15 years the game has been shredded and minmaxed to the point where everyone knows every single packet and opcode, these "classic" expansions were replayed by millions of ppl over and over and over again, the competitive community knows damn well what is or isnt good for the game. Why listen to ppl who have no idea instead?

**Comment by ManneN1** [comment]
Fully agreed.

**Comment by Oliaxz** [comment]
Heres a bluepost from 2009 where blizzard admits that nitro boost cannot be balanced for arena and that they have no acceptable solution.
 
Blizzard has done nothing new to balance nitro boost and so this blue boost is just as relevant today as it was in 2009 : https://www.bluetracker.gg/wow/topic/us-en/17223045345-nitro-boosts-shut-down-in-arena/

**Comment by perpabc** [comment]
Guesswork when evidence is already available is one of the reasons WoW has become a sinking ship for a decade. Re-read that. We don't need to assume players want things when they've already been tried & tested.

WotLK and Vanilla are by far the most popular WoW versions to date, backed up by emulation statistics. Players of all experience levels spoke up when changes were made to Blizzard's relaunch of Vanilla that weren't in tune with what they wanted, and we're now doing the same thing for Wrath.

One of the sole reasons private servers are popular is because they're made by players who want to play a game that isn't available anymore, which makes them a lot more in tune with the community and it's wishes. They aren't restricted by everything a massive company like Blizzard is re development and game choices, so please listen to the thousands of fans that have been passionately playing this game for years.

You've got loads of people here who have been playing this game for years, of all levels, trying to help you understand where you may not, what the general playerbase wants and filling in the gap for where they may not understand yet, with evidence and logic. We don't need a willynilly "whatever bro let's just throw this in and we'll see if they like it". Terrible way to poison a game that's already established. With a new game, sure. Not with Wrath.

Private servers don't have nitro boosts in Arena because the hundreds of thousands of people playing them, don't want them. It's not rocket science. Absolutely absurd speed boost on tiny little maps where the deciding factor on whether you win is if you kill the enemy. It's a small scale deathmatch. What happens when you give melee classes a tool like this to connect on someone without an escape? It's also not as simple as "well everyone has it!" because some classes can clear slows, snares and stuns where others can't, so they will exponentially scale better with a speed boost that allows you to clear entire maps in seconds, much better than the classes that don't.

Please reconsider. Don't turn this game into a clown show. You have a chance here with Wrath to show the world you still care about this product.

**Comment by CharWS** [comment]
Please leave posts to adding additional evidence or information about the issue. If you want to discuss your feelings on a topic you're welcome to do so on the forums

**Comment by perpabc** [comment]
> Please leave posts to adding additional evidence or information about the issue. If you want to discuss your feelings on a topic you're welcome to do so on the forums

1. They don't read the forums 
2. My post had information on the issue.

**Comment by Evolvee** [comment]
https://twitter.com/BrianBirming/status/1563331927666352128

😂.oO(😡)
