### ISSUE TITLE
[BUG] Debuff Icons on Pet Frame

### ISSUE THREAD

**Issue by YellowTonka** [JamminL/wotlk-classic-bugs#362]
#### 1.1. Description
Debuff Icons are not displayed on Pet Frame
Buff Icons are displayed on Pet Frame
  #### 1.2. How to Reproduce
           1. Summon Pet as Warlock
           2. Have someone apply a Debuff to your pet
           3. Notice there is no Debuff Icon on Pet Frame
  #### 1.3  Source Material

![Screenshot 2022-08-27 010803](https://user-images.githubusercontent.com/111467176/187050048-cbd4952f-dcc7-4d4a-8ddb-c7f227665f1c.png)

#### 2.1. Description
Debuff Icons are displayed on Pet Frame
Buff Icons are not displayed on Pet Frame
  #### 2.2 Source Material
https://youtu.be/Tqgv_tc4dKE?t=28

**Comment by Evolvee** [comment]
This issue is in there since day 1 of Classic TBC as well.

There _might_ also be an issue with PartyMemberFrame1/2/3/4/5 debuff position - certain debuff auras are being positioned right to the frame instead of being below. I have never seen such behavior before. (I didnt research this at all yet, its possible there is some toggle or cvar in the UI and im just dumb af).
