### ISSUE TITLE
[BUG] Aiming Typhoon on an incline prevents ESC from being used

### ISSUE THREAD

**Issue by zacjen** [JamminL/wotlk-classic-bugs#390]
#### 1.1. Description
Esc (or whatever the main menu is configured to) should open whenever you press the button. It also cancels spellcasts when used. Currently, using typhoon (balance druid spell) on an incline will visually bug when cast and then prevent the main menu button from being utilized until you change zones or reload.
  #### 1.2. How to Reproduce
           1. Cast typhoon up an incline (AV, outside shattrah, there's so many places)
           2. Try to press escape 
           3. Be super sad.
           4. Exit and enter an instance to repeat.
  #### 1.3  Source Material
Don't have any good ways to show the escape button not working besides people complaining about it on discord
#### 2.1. Description
A visual bug from typhoon should not prevent you from using the escape button

**Comment by Pomptime** [comment]
Can confirm, and it's super annoying. It happens if Typhoon animation is interrupted by anything, not only slopes. You can cast Typhoon into the wall, and it will completely brake ESC button usage, expect you can close the main menu with it, but can't close or do anything else. Also, almost always your auto-attack is blocked, and you can't start in even with macro or clicking the spellbook icon. Also, cast sound and animation glitches, since the game seems to think that you're still casting. The only way out of this is relog or teleportation loads. /reload won't work.

**Comment by watchyoursixx** [comment]
is this for the druid or someone hit by the typhoon?

**Comment by Pomptime** [comment]
> is this for the druid or someone hit by the typhoon?

Druid

**Comment by watchyoursixx** [comment]
![image](https://user-images.githubusercontent.com/47162044/188512407-108c0945-3ada-4bff-adee-ec49a3cb08ef.png)
Casting typhoon on an inclined surface approximately angled this much or steeper (in the above pic) does indeed cause the keybind for the main menu to fail.

It also prevents any mounting animations to play. There may be other animations frozen by this but I didn't notice.

You can still click the menu button at the bottom however.

**Comment by zacjen** [comment]
Just additional information about "resetting",

**Comment by SnyzRogue** [comment]
I noticed it also makes any animation, such as /lol or even seathing your weapon not function at all. Also completely bugs out the castbar.

**Comment by watchyoursixx** [comment]
hotfixed 10/21
