### ISSUE TITLE
[#SomeChanges Suggestion] Increase MMR + rating cap as the Arena season progresses

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#405]
Currently, high-end Arena players reach a brick wall in progression when they hit the rating cap of 3126, causing the ladder to bottleneck.

This isn't an issue in other competitive titles as there are systems in place to either have a constant revolving door of players at the top, or an infinite amount of MMR progression possible within a season of play. 

Adopting the retail system (no rating cap, progressive mmr cap over the season) for Wrath with the upcoming abundance of PvPers returning would be ideal.

**Comment by Evolvee** [comment]
I think the issue isnt necessarily the cap itself, the issue is also that **the current MMR system is auto-self-inflating.** The more people play, the higher everyone gets. There is no decay whatsoever. If it wasnt completely linear, it would be way harder to reach such rating - only the most consistent players (and comps) would be able to reach it. Its so bad that there was literally ZERO DIFFERENCE between teams you meet at 2800 MMR and teams you meet at 3000 MMR. It was extremely easy to gain MMR, but it was also extremely easy to lose MMR if you got unlucky loss streak. With the current system, you gain the same exact MMR at 2k as you gain at 3k.. +/- 25 MMR per game at such a high bracket as 3k just doesnt make any sense. Imho, the skill gaps of participating arena teams should be distinquished way more.

Back then _(TBC)_ the arena team system ensured there isnt that many 2.2k+ arena teams due to these teams winning +1 rating and losing -30. While that system is obviously cancerous, especially due to the current minmaxing community mentality, it should be in some way atleast incomporated into the MMR system so that you dont gain that much MMR at higher bracket and you are forced to play your way up over multiple of arena queues instead of the current _"getting 3k within 1 day"_ meta.

The MMR cap issue is a byproduct of this ^^ problem. The fact its actually capped doesnt make any sense either tho. I would understand if they capped it due to increased arena point gain at such rating but there is literally 0 difference between 3100 2s and 2800 2s when it comes to AP flush.

![image](https://user-images.githubusercontent.com/1942409/189732389-75e33754-c4b1-4d52-8857-b38a578a9020.png)

Obviously, even this ^^ isnt perfect. Not at all. It punishes the high rated teams and deters them from playing since every loss would be way more devastating than with the previous system. Unless there is some change though, even the removal of the MMR cap will not entirely solve that much - the highest MMR teams will only get as high as long the season is. Longer season = Higher MMR, instead of the desired Better players = Higher mmr.
