### ISSUE TITLE
[BUG] Da Voodoo Shuffle + Shadowpriest Mindflay interaction

### ISSUE THREAD

**Issue by nistra123** [JamminL/wotlk-classic-bugs#414]
#### 1.1. Description

Troll Mind Flay is 2.55 seconds base instead of 3.00 seconds and will do all 3 ticks, this is because of a bugged interaction between Da Voodoo Shuffle and Mind Flay. (NOT TALKING ABOUT BERSERKING)

  #### 1.2. How to Reproduce

           1. Play a Troll Shadowpriest and Cast Mind Flay on a Target Dummy.        
       
  #### 1.3  Source Material

https://clips.twitch.tv/RepleteNastyFennelStrawBeary-dJfcWUSB94TSSjuz

 ### 2. Expected Behavior

It should work like it works for all other races.

**Comment by caccavale** [comment]
Also seems to be caused by snare duration meta gem.

**Comment by dbyena** [comment]
Known interaction since Vanilla Classic with the effect of Mind Flay vs Enhancement shamans with Toughness talented. Slow reduction lowers cast time of channeled Mind Flay.

**Comment by Evolvee** [comment]
The Toughness interaction is perfectly Blizzlike. This on the other hand makes 0 sense whatsoever. If the mindflay was casted on a troll, yea sure, but in this bugreport the issue is that its the troll who is the spell caster/action invoker of the spellcast and no matter who is the victim, it acts as if the victim was troll (snare duration reduction).

This is a veeeery big shot in the dark but it might have to do something with incorrect behavior of the Mind Flay´s interrupt flag that could potentially act like the shadow priest is affected by root/snare due to being forced to stand on 1 spot while channeling and then the troll racial applies to it.
![image](https://user-images.githubusercontent.com/1942409/190508822-461db704-c2bf-44b1-b2f0-c71063e2b8cd.png)

**Comment by watchyoursixx** [comment]
hotfixed 10/19/22
