### ISSUE TITLE
[BUG] Glyph of Death Strike incorrect

### ISSUE THREAD

**Issue by vigo2** [JamminL/wotlk-classic-bugs#424]
Glyph of Death Strike's tooltip reads "Increases your Death Strike's damage by 1% for every 1 runic power you currently have (up to a maximum of 25%)."

While it does indeed increase DS damage up to 25%, it scales with 1% for every _2_ runic power, reaching maximum damage at 50 runic power instead of at 25 runic power.

This can easily be reproduced vs. a target dummy using the various 2-4 damage vendor weapons, and observing the damage multipliers compared to the 0 runic power baseline.

According to patch notes, the "1% damage for every 2 runic power" scaling was introduced in Patch 3.1.0. It might have been buffed in later patches, but that's not mentioned in patch notes, as far as I researched.

**Comment by dummyaccounter** [comment]
I have confirmed this bug. I hope this can be fixed.  I used a vendor weapon with minimal dmg spread. 


BUG: 
-death strike glyph adds the wrong damage
-death strike glyph dmg bonus scales from 0-50 RP instead of scaling from 0-25 RP
 

Death strikes at 0 RP:  1312, 1311, 1314, 1312
Death strikes at 25 RP: 1480, 1485, 1479, 1478, 1478, 1484
Death strikes at 50 RP: 1642, 1645, 1643, 1641, 1640
Death strikes at 100-130 RP: same numbers as 50 RP

These numbers are consistent with OP's numbers that live version is scaling 0-50 runic power instead of 0-25 runic power.


I was looking for other versions of this glyph in wikis in case the wrong glyph got implemented but it seems like it's the "right glyph" but the numbers are just off. Here are some versions of this glyph for reference:

Previous version which was more powerful https://wowpedia.fandom.com/wiki/Glyph_of_Death_Strike?oldid=2031813
1% dmg AND healing per 1 runic power, capped at +25% dmg/heal bonus

Current live version https://wowpedia.fandom.com/wiki/Glyph_of_Death_Strike?oldid=2194835 
1% dmg per 1 runic power, capped at +25% dmg bonus

Reworked version afterward https://wowpedia.fandom.com/wiki/Glyph_of_Death_Strike?oldid=2438674
2% dmg per 5 runic power, capped at +40% dmg bonus

**Comment by dummyaccounter** [comment]
"[CharWS](https://github.com/CharWS) changed the title 
[BUG] Glyph of Death Strike doesn't scale as advertised --> [BUG] Glyph of Death Strike incorrect tooltip 
[29 minutes ago]"

I am not sure if "glyph of death strike incorrect tooltip" is a proper description of this, because there are no versions of the glyph in patch notes as far as I am aware that accurately represent the current live wotlk classic behavior

**Comment by CharWS** [comment]
1% damage per 2 runic power is consistent with the 3.1.0 patch notes, if there's no other confirmable sources as to a change following that then it would simply be an incorrect tooltip on the glyph

**Comment by dummyaccounter** [comment]
I was able to find some meager evidence, a video where the video creator advises people to only use death strike at >25 runic power.

```April 14, 2009 [Glyph of Death Strike]: This glyph now increases  [Death Strike] damage by 1% per 2 runic power, but has a limit of 25% increase.

Patch 3.1.0```

```Aug 19, 2010
 [TheWoWcorneR] https://www.youtube.com/watch?v=gYPgO_SZut4
Major Glyphs:
-Glyph of Death Strike: make sure you use Death Strike while you have 25 or more runic power ;)```

Their last video upload was 11 years ago so I doubt they changed the video description. This video was created 1.5 years after the 3.1.0 patch notes. And again, the wiki also multiple historical entries listing the spell as maxing out 25 runic power, though, yeah, I suppose the wiki can only be as accurate and up-to-date as the people editing it.

**Comment by NuptupTDOW** [comment]
> This isn't definitive proof but I feel like it wouldn't make sense for him to advise "not casting unless 25+" if it needed 50+ to deal full damage

Don't get me wrong, I think having it scale from 25 instead of 50 would be more beneficial, but you also need to consider that if the 3.1.0 version IS the correct version, and it's the one we have now, then that video maker could have said 25 Runic power simply because that's what the tooltip said back then as well, and it's just been incorrect this entire time even back then. Also, I vaguely remember always making sure I had 1 point in Runic Power Mastery back in the day so I could only be 1 hit away from getting back to that +25% damage after 2 death coils. I would assume I had done the testing to make sure it worked, but I could have also been wrong. 

As a Blood main though, I genuinely think either option would be fine, whether it's fixing the tooltip to reflect 1% for 2 RP, or adjusting it to 1% for 1 RP to match the existing tooltip. For DPS Blood DK's, it will only be a marginal increase to damage when played optimally, but Blood DPS could use a small bit of love if we're being honest, so the 1% for 1 RP option would be non-intrusive, slight buff to a weak dps spec, and not really provide any negatives anywhere else.

**Comment by dummyaccounter** [comment]
Interestingly enough, I was not able to find a patch note that mentioned dancing rune weapon duration glyph getting nerfed from +10s to +5s, and yet I was able to find a video from a few months before the Cataclysm prepatch showing the player's dancing rune weapon only having +5s bonus duration (12s baseline, 5s more with glyph). So I'm not sure if the patch notes are the end-all be-all (for things such as death strike glyph), or, perhaps I just missed it despite searching thru every patch note between 3.1.0 and Ruby Sanctum

**Comment by danniellos94** [comment]
There is also 3.2.0 patch where the death strike tooltip glyph is corrected I guess so if it was corrected why we have 1% per 1 runic power ? Here guide from March 2010 also saying you need 25 runic power to increase damage to 25%.
https://youtu.be/_DrkvXs4Ous?t=194

**Comment by danniellos94** [comment]
https://youtu.be/221jtKbsWQA?t=84 20 runic power 4464 horn 3x bloody vengeance t10 set bonus fallen crusader. wfs, 2x stack of indomitable

https://youtu.be/221jtKbsWQA 76 runic power 4713 death strike  buffs : horn 3x bloody vengeance t10 set bonus fallen crusader 1 stack of indomitable, wfs

Assuming 1% dmg per 2 runic ( up to 25%) power this would be 10% dmg timestamp and 25% in second
110%=4464
so 100% would be 4058
then 125% would be 5072.5

Assuming 1% dmg per 1 runic power
120%=4464
100%=3720
then 125% would be 4650 = this is much closer

Of course there is weapon diff and this 1 stack of indomitable but this is most likely 1% per 1 runic power.

**Comment by watchyoursixx** [comment]
hotfixed 10/21
