### ISSUE TITLE
[#SomeChanges Suggestion] Account-bound items should be Battle.net wide

### ISSUE THREAD

**Issue by battlernet** [JamminL/wotlk-classic-bugs#435]
## Existing Behavior

Currently when trying to mail [Tome of Cold Weather Flying](https://www.wowhead.com/wotlk/item=49177/tome-of-cold-weather-flight) across accounts under the same Battle.net account, the warning "Account-bound items can only be given to your own characters.

## Proposed Change

Since Battle.net in its current form was not around in original Wrath of the Lich King Classic, I don't think that this behavior is qualified as a bug. In The Burning Crusade, Blizzard adapted the previously account-bound instant mail feature to be Battle.net account wide. I propose that the same should be done for account-bound items in Wrath of the Lich King Classic.

Thanks!

**Comment by NuptupTDOW** [comment]
Would this also apply to things such as BoA items for leveling alts across multiple classic accounts? Or would it only apply for "Consumable" things? I ask because, I could see a scenario where someone sends their BoA to an alt on their 2nd account and then forgets to pull that item off of that account before letting a subscription expire, then blaming Blizz for not just going the retail route and adding a "BoA Box" that your entire account can access. 

I'm not necessarily for or against this idea overall since I see the pros and cons of both sides, but I feel like it's something worth mentioning before making a vast change due to one item in particular. And, while those of us with two accounts may definitely like this idea because it means cross-account alts would fly right away, I want to clarify that this is currently working as it was back then. Anyone who had 2 accounts back then still needed to actually get CWF once on each WoW account, not just once overall, since there was no account association. Same goes for BoA's. 

I'd be happy to see this idea come through and get implemented, but I felt I could/should voice my concerns with it as well.

**Comment by watchyoursixx** [comment]
this should be fixed now
