### ISSUE TITLE
[BUG] [Core] [Spell] Dots refreshed via other spells ending before their full duration

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#439]
### 1. Current Behavior

https://www.youtube.com/watch?v=EsAXy0sExsg

When SW: Pain is refreshed with Mind Flay while having "Pain and Suffering" talent, the real duration of the SW: Pain doesnt match the displayed debuff duration - the aura is removed earlier which makes it impossible to further refresh it at the end of its duration with Mind Flay again.

https://www.wowhead.com/wotlk/spell=48125/shadow-word-pain
https://www.wowhead.com/wotlk/spell=48156/mind-flay
https://www.wowhead.com/wotlk/spell=47582/pain-and-suffering

This behavior might be caused by the fact that there are no more ticks in the SW: Pain at the final tick (while the debuff still has 1-2 seconds to go) so the server just removes the debuff because its "useless"... Usually all dots have the final tick at the debuff removal, however its not the case here so thats why its behaving this way...

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Make priest
           2. Learn sw: pain and mind flay
           4. learn pain and suffering 3/3
           5. do what you can see in the video above
           6. observe the same result

#### 2.1. Description

The duration should probably correspond with what you can see ingame without the aura disappearing out of nowhere.

  #### 2.2 Source Material
∅
Nothing yet.

**Comment by JamminL** [comment]
Before I confirm this, could you test without addons? To be absolutely sure, I'm sure it's still bugged

**Comment by YellowTonka** [comment]
This is not a Bug. Every fresh SWP through Pain and Suffering has to have the same number of ticks. Usually with a hard cast SWP the first tick happens 3 sec into the debuff. Whereas when refreshed via (Pain and Suffering) in order to not delay the continuity of Ticks, the first tick will happen earlier than 3 sec after reapply. The new SWP has the same debuff duration as a Hard cast SWP and the same number of Ticks, but the Ticks just occur earlier throughout

**Comment by YellowTonka** [comment]
The same occurs with Everlasting Affliction and Corruption for warlocks

**Comment by watchyoursixx** [comment]
The same also with serpent sting and chimera shot refreshing it.

If you refresh it with 1 sec remaining on the next tick, the next tick will still happen 1 sec later, but the dot is refreshed to 15s. So each tick still stays same interval, but now the 5th tick happens at 13 s instead of 15s and the last 2 s nothing happens. The aura does maintain visually though, unlike what if suggested here where the visual disappeared even though there is duration shown.

**Comment by sneakyverill** [comment]
Regarding SWP 
1) The SW:P behavior of dropping the debuff early was in original wotlk. If it is a bug, it got carried into classic.
2) The exact moment the debuff drops, is at the last tick that fits the refreshed window (SW:P is not a hasted ability)

Regarding Corruption and Chimera (Serpent Sting)
1) We have encountered several cases during research where the corruption debuff does not drop after the last tick that fits the duration, and actually results in an additional tick at the end. In other words, we witnessed 2 full dmg ticks with less than 1s between them (backed by combat log).
2) In case the dot does not fall, refreshing it beyond the last tick that fits the window is considered a cast by the server and not refresh. That is why you will experience a longer delay before you see a damage instance. This is true for rogue deadly poison refreshes, chimera shot refreshing stings etc

**Comment by raethkcj** [comment]
This bug also applies to [Elemental Shaman's T10 4pc bonus](https://www.wowhead.com/wotlk/spell=70817/item-shaman-t10-elemental-4p-bonus), causing us to choose between clipping Flame Shock, losing the guaranteed crit effect of Lava Burst, or creating a third-party solution that overwrites the UnitAura API's behavior.
