### ISSUE TITLE
[BUG] Critical Bug!!!! Max level gold from quests (Repost with proof)

### ISSUE THREAD

**Issue by NatsumeLily** [JamminL/wotlk-classic-bugs#452]
#### 1.1. Description
When you are max level you get exp converted gold and base quest gold.
  #### 1.3  Source Material
Quest giving incorrect value. 
![image](https://user-images.githubusercontent.com/15247730/194683858-3830ed62-e083-4c47-a223-5d95b3ec3df3.png)
#### 2.1. Description
You should only get one of the values, which ever is higher. Base quest gold or exp converted gold. 
  #### 2.2 Source Material
https://wowpedia.fandom.com/wiki/Experience_point
![image](https://user-images.githubusercontent.com/15247730/194683949-0c39f89b-42d0-4215-8a60-4a3b1696ec3e.png)

https://wotlkdb.com/?quest=14457 - This database says the quest should give 20g at max level, and it likely does with the current bug. 
This video shows the quest giving 13g at max level, which is correct. 
https://youtu.be/XsCkOp33oqE?t=248 

https://wotlkdb.com/?quest=13862 - Site says 20g
https://www.wowhead.com/wotlk/forums/topic/lvl-80-quest-gold-rewards-106632
![image](https://user-images.githubusercontent.com/15247730/194684319-fcfd93cb-3366-4a41-8777-52a926b84372.png)

https://www.wowhead.com/wotlk/forums/topic/lvl-80-quest-gold-rewards-106632
![image](https://user-images.githubusercontent.com/15247730/194684335-0aeeb3c6-679e-4cb1-87e2-365b374b726a.png)

**Comment by NatsumeLily** [comment]
There's some proof. I thought I wouldn't need to since the only people who think this isn't a bug are idiots from warmane.

**Comment by watchyoursixx** [comment]
You _always_ need proof otherwise how do you know it's bugged?

in the link you provided as proof:
![image](https://user-images.githubusercontent.com/47162044/194687799-a5c7f27b-fc6c-414f-9ba0-2372e133982c.png)
This is from the historical changepoint of https://wowpedia.fandom.com/wiki/Experience_point?oldid=2573306
which was changed jan 2011 for Cataclysm.
This was pre-jan 2011, wording from your "source": 
![image](https://user-images.githubusercontent.com/47162044/194687844-937fe827-63f0-4ebd-a36b-7fad10078864.png)
From https://wowpedia.fandom.com/wiki/Experience_point?oldid=2568926

Not very cut and dry on whether the latter is true or not which states "you get gold instead of experience", not "you get gold + bonus gold converted from experience" or "you only get gold instead of gold and experience"

It's not a good explanation and the only "explanation" was post Cata.

The above ss's from wowhead are dated 3.0 and 3.1 patches, so how do we know there wasn't a buff in-between? The comments on wowhead also don't give actual examples, just "I feel I only got this amount"

Not saying that it's not bugged for sure, just saying that according to the research all we "know" for sure is that exp is converted to gold at 1 xp = 6 copper, per multiple sources throughout wotlk and early Cata. The other information is just speculation based on comments that are speculating what they remember, not actual results and facts.

The other side of things, is why would they fix it now after people already spent a couple weeks earning "more" if this was bugged? suddenly they change it and now people don't want to quest because the rewards are crap. The "cat is out of the bag" so to speak, at the very least. This is also a minor thing imo, not a "Critical bug". Increasing the gold floor is a good thing for those that actually spend some time doing the quests, vs those that hate questing and just want to zug zug dungeons.

I'll put a "research needed" tag on it until more clear evidence can be found and possibly some insight from blizz into it.

**Comment by Aggrend** [comment]
Not a Bug.
