### ISSUE TITLE
[#SomeChanges Suggestion] Shadowmeld Consistency

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#476]
### The situation
Shadowmeld in wotlk got revamped and it is now usable while in combat. This made Nightelf a much more appealing race as it gave this ability a bunch of different uses that were not possible before:

 1. Could be used in PvP to instantly drop combat and drink, revive or mount
 3. Could be used in PvP to instantly drop combat and stealth, allowing classes like druids/rogues to enter prowl/stealth and use stealth abilities mid-combat
 4. Could be used to cancel both normal and channeled casts on you during combat, even if caster is nearby
 5. Could be used to immune spells that have a travel-time if timed properly while the spell is in the air
 6. Could be used to immune instant spells if shadowmeld was cast at the same exact batch the other cast
 7. Can be used in PvE to de-aggro mobs for the duration of the shadowmeld
 8. Could be used to become invisible, making pets de-target you
 
 However, it was recently discovered that during wotlk, shadowmeld would stop functioning under certain "hidden" conditions. These hidden conditions, after tests, will mostly only affect Arenas and Dungeons. If these certain conditions apply, shadowmeld uses are reduced to the following:
 
 ~~1. Could be used in PvP to instantly drop combat and drink, revive or mount~~
~~2. Could be used in PvP to instantly drop combat and stealth, allowing classes like druids/rogues to enter prowl/stealth and use stealth abilities mid-combat~~
 ~~3. Could be used to cancel normal and channeled casts on you during combat, even if caster is nearby~~
 ~~4. Could be used to immune spells that have a travel-time if timed properly while the spell is in the air~~
~~5. Could be used to immune instant spells if shadowmeld was cast at the same exact batch the other cast~~
~~6. Can be used in PvE to de-aggro mobs for the duration of the shadowmeld~~
 7. Could be used to become invisible, making pets de-target you
 
Based on tests, shadowmeld works perfectly fine, as expected, anytime the NightElf has no allies nearby. This means that it'll work perfectly in duels, it'll work in solo WorldPvP or in BGs in situations the Nightelf is 1vX, and even in arena situations! Here are some original 3.3.5a clips where meld works as expected:

- WPVP 1v3 - Immune Spell + Drop Combat: https://youtu.be/sXd-AstxVrU?t=377
- WPVP 1v2 - Immune Spell + Drop Combat: https://youtu.be/sXd-AstxVrU?t=702
- BG 1v1  - Immune Spell + Drop Combat: https://youtu.be/sXd-AstxVrU?t=421
- BG 1v1 - Drop Combat https://youtu.be/EqLPKtBlOmw?t=311
- BG 1v2 - Immune Spell + Drop Combat: https://youtu.be/sXd-AstxVrU?t=1028
- BG 1vX - Drop Combat https://youtu.be/ZZGE1eCouYo?t=51
- Arena 1v2  -  Drop Combat https://youtu.be/zzLaos13gYM?t=329
- Arena 1v2 - Drop Combat https://youtu.be/-tavyO16Phg?t=36
- Arena 1V1 + Immune Spell + Drop Combat  - https://youtu.be/7lNDvYEXAII?t=33 (partner was stealthed and OOC so doesn't count)

However, once you have a partner in combat that you have interacted with, the shadowmeld stops working as expected:
- Arena 2v1 https://www.youtube.com/watch?v=7lNDvYEXAII&t=283s
- Arena 2v2 https://www.youtube.com/watch?v=Lset0GJ0uYc&t=212s

Testing on Beta, one of these conditions seems to be related to auras. If the nightelf buffs a partner, or gets buffed by the partner, shadowmeld stops working:
- Nightelf buffs someone else:
  1) Rogue is in combat
  2) Druid buffs rogue with lifebloom
  3) Druid Shadowmelds
  4) Shadowmeld fails to work
https://streamable.com/by7yg6
- Nightelf gets buffed
   1) Rogue is in combat
   2) Druid buffs rogue with gift of the wild
   3) Rogue shadowmelds
   4) Shadowmeld fails to work
https://streamable.com/ibupit

### Consequences

This behavior, in essence, results in shadowmeld being only useful for solo battles, and will become a completely useless racial in situations where you play with friends such as Arena, BGs, Dungeons - Thereby making character boosts (and leveled Nightelves) feel like they now have to reroll.

### The ask

Change the ability to be consistent. It should act the same way in multiple friendlies situation as it does in solo content, allowing combat to drop instantly in almost every situation and allowing spells to be immuned if timed properly.

- Pros
  1) Player Expectations 
      - Players do not understand why the ability at times is completely useless, vs sometimes when it works perfectly - Inconsistency is just frustration.
      - Players have seen this ability work the same way it does in solo content throughout every other wow expansion, it seems this inconsistency was addressed in 4.0.1 per video evidence, and it never again stopped functioning as intended, even in multi friendly-player content.
      - Another small but important reason is that people have already made their race choices, and with no race-change they are now stuck with probably the only racial that has no use in end-game content.
    2) Iconic Ability
          - It's one of these iconic abilities in PvP where it requires a fast reaction time or a good game-sense to predict a spell and immune it. It's been seen throughout every WoW expansion being used by top-players ingame, in youtube videos and now on streams.
    3) Game Design
          - Racials in general are famously imbalanced on Wotlk. Nightelfs were a "fun" viable option for people not wanting to follow the min-max meta where you'd still be left with a high-risk/high-reward ability, often a trade-off of damage for utility. Whereas in this state, they are absolutely useless for both end-PvP and end-PvE content.
          - For classes that are forced to go nightelf, druids, this means that if they go alliance, they get 0 value out of their racial. A class that especially underpeforms in wotlk on all specs (except feral - compounded by current bugs). Shadowmeld has historically been a small buff to these specs
- Cons
    1) Not intentional Design
        - While the intent might've been to have shadowmeld underpeform and not be considered a vanish, it's long been proven that the expected behavior of shadowmeld is actually an added benefit to the game. It's a fun, iconic ability that adds to balance and race-diversity. It is also the behavior that has been seen since 4.0.1 all the way to the current modern wow versions. Additionally, if the original design intent was to make shadowmeld not work in grouped PvP, even this intent is not applied consistently, as certain arena comps can void this restriction (e.g double rogue) and use shadowmeld as a another vanish anyway.
    2) Development Time
        - This is probably the biggest grievance of such a change, as player support and the fact that it's good design should already be a given. Understandibly, a change like this will take some time to develop, especially since it meshes with one of the foundational systems - combat. That said, considering the large amount of playerbase currently affected (disappointed) by this, and considering there's some helpful ways to shorten the time and risks (basing on a similar ability like Vanish, or even backporting recent iterations of shadowmeld) I really do think it's worth it.

**Comment by imaslakov** [comment]
"except feral - compounded by current bugs" do you mean feral has got any bugs right now? Which bugs?

**Comment by NuptupTDOW** [comment]
> "except feral - compounded by current bugs" do you mean feral has got any bugs right now? Which bugs?

https://github.com/JamminL/wotlk-classic-bugs/issues?q=is%3Aissue+is%3Aopen+label%3ADruid

That's a list of all active, open druid bugs. Based on titles, you can probably figure out which ones you will specifically be interested in.

**Comment by JamminL** [comment]
> "except feral - compounded by current bugs" do you mean feral has got any bugs right now? Which bugs?



> > "except feral - compounded by current bugs" do you mean feral has got any bugs right now? Which bugs?
> 
> https://github.com/JamminL/wotlk-classic-bugs/issues?q=is%3Aissue+is%3Aopen+label%3ADruid
> 
> That's a list of all active, open druid bugs. Based on titles, you can probably figure out which ones you will specifically be interested in.

<https://github.com/JamminL/wotlk-classic-bugs/issues/255> Specifically this, it's not specific to feral but they benefit the most from this issue

**Comment by NuptupTDOW** [comment]
Gotcha. Thank you for the clarification. 

Also, since I assume you've got a more direct line of communication to the team than most of us do, has there been any concrete mention in the past 90 days since it was originally reported on if they are even remotely considering doing anything or are even aware that something is in fact working incorrectly? I've been doing my best to stay on top of blue posts and checking patch notes and whatnot, but I really haven't seen anything mentioning this at all. 

If my assumption is wrong and you're just like the rest of us, unable to directly communicate with the team, feel free to ignore this, but I am only making the assumption based on you being the lead for this github and my own potentially flawed assumption that github of all places is where the classic team is doing their bug-tracking. Maybe I'm being naïve, or maybe it is intentionally in a community accessible location for the playerbase to have interaction and ease of reporting, but I've no clue what the situation is, so I'm just assuming the guy in charge, might be more informed than myself and others. 

Either way though, thank you for such a thoroughly thought out write up on this issue. It's one of the more in-depth ones I've seen, and on this issue in particular, I'm very passionately awaiting an update as it's genuinely one of my favorite things about my original death knight, and it's been very hit or miss in wrath classic.

**Comment by JamminL** [comment]
> Gotcha. Thank you for the clarification.
> 
> Also, since I assume you've got a more direct line of communication to the team than most of us do, has there been any concrete mention in the past 90 days since it was originally reported on if they are even remotely considering doing anything or are even aware that something is in fact working incorrectly? I've been doing my best to stay on top of blue posts and checking patch notes and whatnot, but I really haven't seen anything mentioning this at all.
> 
> If my assumption is wrong and you're just like the rest of us, unable to directly communicate with the team, feel free to ignore this, but I am only making the assumption based on you being the lead for this github and my own potentially flawed assumption that github of all places is where the classic team is doing their bug-tracking. Maybe I'm being naïve, or maybe it is intentionally in a community accessible location for the playerbase to have interaction and ease of reporting, but I've no clue what the situation is, so I'm just assuming the guy in charge, might be more informed than myself and others.
> 
> Either way though, thank you for such a thoroughly thought out write up on this issue. It's one of the more in-depth ones I've seen, and on this issue in particular, I'm very passionately awaiting an update as it's genuinely one of my favorite things about my original death knight, and it's been very hit or miss in wrath classic.

What issue specifically are you talking about?

**Comment by imaslakov** [comment]
> > Gotcha. Thank you for the clarification.
> > Also, since I assume you've got a more direct line of communication to the team than most of us do, has there been any concrete mention in the past 90 days since it was originally reported on if they are even remotely considering doing anything or are even aware that something is in fact working incorrectly? I've been doing my best to stay on top of blue posts and checking patch notes and whatnot, but I really haven't seen anything mentioning this at all.
> > If my assumption is wrong and you're just like the rest of us, unable to directly communicate with the team, feel free to ignore this, but I am only making the assumption based on you being the lead for this github and my own potentially flawed assumption that github of all places is where the classic team is doing their bug-tracking. Maybe I'm being naïve, or maybe it is intentionally in a community accessible location for the playerbase to have interaction and ease of reporting, but I've no clue what the situation is, so I'm just assuming the guy in charge, might be more informed than myself and others.
> > Either way though, thank you for such a thoroughly thought out write up on this issue. It's one of the more in-depth ones I've seen, and on this issue in particular, I'm very passionately awaiting an update as it's genuinely one of my favorite things about my original death knight, and it's been very hit or miss in wrath classic.
> 
> What issue specifically are you talking about?

He is talking about shadowmeld :)

**Comment by NuptupTDOW** [comment]
> What issue specifically are you talking about?

Sorry, should have clarified. I'm wanting to know if there's any information beyond the wealth shared here on github about Shadowmeld and how it is "working" currently. 

I've read every issue, open or closed that even has the word shadowmeld in it to try and make any sense of it, at least with your write up I know how and why it fails. Now I'm just wondering if there's any information from official sources that recognizes the issue exists, and plans to resolve it in any way?

**Comment by JamminL** [comment]
Right, so regarding shadowmeld there's a reason this issue is in the "#SomeChanges" Category . It seems to behaves exactly like it did originally in 3.3.5a (some examples in the post). So technically speaking this is Not a Bug. This is obviously a huge disappointment for most of us, and that's why we opened up this petition. 

They're aware of this (they monitor this github). We've plead our case, now it's up for them to decide to keep this behavior or change it in some way more alligned with player expectations.

**Comment by NuptupTDOW** [comment]
Sometimes, I genuinely wish I could go back in time. I would just, give past me a 5 terabyte external drive and say "Record every second of WoW you ever play from now on, I'll need it later." and just move on. Because.., I swear, on everything I own, that the way Shadowmeld is _currently_ working on Wrath Classic is not how it worked on Wrath Original. Whether I'm believe, whether there's proof or not, I refuse to believe that this buggy mess of a racial ability was like this back then. At that time, I was in junior high and early high school, playing entirely too much, and dumping hours upon hours of time into my one character (Nelf Dk), and I have zero memories of ever being upset that it failed, or wondering why it didn't work, or anything. My entire group of friends that returned for Wrath Classic have vivid memories of goofy mistaken pulls and having to recover through Shadowmeld use and it simply doesn't work like that. 

I will fully admit that I was young at the time, but I remember specifically THIS PART working near flawlessly, every single time. "6. Can be used in PvE to de-aggro mobs for the duration of the shadowmeld." I remember being in dungeons, open world, and in raids, and having a very clear death/wipe on the horizon and just saying "I'm not running back, wipe it up." and then hitting shadowmeld and watching whatever boss de-aggro me as the tank and slaughter the rest of the raid, then just despawn/reset as I move back to the waiting area. That's fully buffed, in a raid, main tanking 25 man festergut for example, seeing the raid fail to whatever mechanic, and just choosing to call the wipe and hit Shadowmeld so I don't have to pay repair bill. I vividly remember situations like this all throughout Wrath. Its the reason I never paid to change to a draenei and have +hit and Gift of Naaru. 

At least according to what I've read in the old thread and in here, it seems like, according to what has been stated, the only way Shadowmeld would cause you to be able to drop threat on a raid boss, in a raid team, is if somehow you've managed to never get a buff from any of your allies, and you've never shared a buff with any of them either, then you might be capable to have use # 6 actually work correctly. But.., that's just not feasible, and clearly not the case in my memories. So, unless I'm just delusional, I really think there's still something that is wrong that isn't even a Some Changes suggestion and is still a bugfix. It seems like about 80% of the focus in the shadowmeld reports is about how it interacts in PvP situations, with most all source examples being from WPVP, BG's and Arenas. But, I haven't seen any decent dives into examples in instanced PVE situations, or many people even bringing that side up. I don't PVP, I haven't ever done a well timed Shadowmeld to cancel a spell or restealth or whatever. I'm a simple tank DK who runs dungeons and raids, and it seems like there's no one else adding a voice for this side of the discussion.

I will make it my personal goal to do my best and find some old youtube videos of night elves using shadowmeld in instanced PVE settings, but I would like to request that others do as well.

**Comment by Evolvee** [comment]
@NuptupTDOW You might remember it correctly, dont worry. Just because Blizzard says it worked this way doesnt rly mean it really did. They were time and time again wrong about multiple mechanics during classic TBC - just remember how often they changed the Cloak of Shadows behavior. It was changed atleast 3 times, and each time they said it corresponds to their reference client/core build behavior... In this post (https://www.wowhead.com/tbc/news/blizzard-explains-bug-fix-regarding-spell-resist-in-burning-crusade-classic-324594) for example they said that one of the previous CoS implementations comes from the behavior of BETA TBC, yea the actual beta of the original TBC... Now compare it with this post where they claim the 80% behavior is NOT A BUG and its correct TBC behavior: 
https://www.wowhead.com/tbc/news/burning-crusade-classic-not-a-bug-list-may-18-2021-322401

The result? After several changes to CoS mechanics we received a version at the beggining of Season 2 TBCC where you could not even wand into CoS..which was NEVER the case on retail. 😂

So yea, thats how reliable the "it worked this way" claim from their part is.

**Comment by NuptupTDOW** [comment]
> @NuptupTDOW You might remember it correctly, dont worry. Just because Blizzard says it worked this way doesnt rly mean it really did. They were time and time again wrong about multiple mechanics during classic TBC - just remember how often they changed the Cloak of Shadows behavior. It was changed atleast 3 times, and each time they said it corresponds to their reference client/core build behavior... In this post (https://www.wowhead.com/tbc/news/blizzard-explains-bug-fix-regarding-spell-resist-in-burning-crusade-classic-324594) for example they said that one of the previous CoS implementations comes from the behavior of BETA TBC, yea the actual beta of the original TBC... Now compare it with this post where they claim the 80% behavior is NOT A BUG and its correct TBC behavior: https://www.wowhead.com/tbc/news/burning-crusade-classic-not-a-bug-list-may-18-2021-322401
> 
> The result? After several changes to CoS mechanics we received a version at the beggining of Season 2 TBCC where you could not even wand into CoS..which was NEVER the case on retail. 😂
> 
> So yea, thats how reliable the "it worked this way" claim from their part is.

Thank you, so so so much. I thought I was going crazy... I'm still gonna look for more evidence, but really, it's hard. And, it's just nice to know that, just because something is deemed N.A.B. and a SomeChanges succession, doesn't actually mean it's not bugged. I'm genuinely, incredibly baffled at why that is the way it's been decided, but whatever I guess. Just gonna do my best to help and be constructive.

**Comment by Macumbatbc** [comment]
`Could be used to become invisible, making pets de-target you`

This bug is in the game since TBC, a huge issue for stealth classes.

**Comment by Jgrenier91** [comment]
Any update on this one?

**Comment by JamminL** [comment]
Suggestion accepted for arena and bgs and currently working on PTR as of 1/10/2023 3.4.1.47496
