### ISSUE TITLE
[BUG] Macro's don't work correctly

### ISSUE THREAD

**Issue by XyzKangUI** [JamminL/wotlk-classic-bugs#479]
### 1. Current Behavior
The macro system is a disaster. 
  #### 1.2. How to Reproduce

Issue 1:

This macro for example would not work properly without adding 'exists':
`/cast [@mouseover, nodead] [@target] Dispel Magic`

The issue in this macro is that it will never skip to the second conditional, being @target. That is because nodead does not seem to look for the existence of an unit, unlike all the other conditionals.

Issue 2:

```
/cast Vanish
/cast [nostance] Backstab
/cast [stance:1/2] Ambush
```

This macro will backstab when you press fast twice. It should be mentioned that this always happends with vanish but (almost) never with shadow dance.

#### 2.1. Description
1. nodead should work without exists
2. [stance] or [nostance] should prevent an ability from being used when the opposite is true

**Comment by raethkcj** [comment]
`/target [harm] Name` works just fine for me. 

It sounds like you're misunderstanding which unit the conditionals apply to. When you don't supply a unit such as `[@target]`, the conditional is evaluated against your current target, *not* the Name you supply after the conditional.

`/target [@name, harm]` won't do anything most of the time, because `@` only works with [Unit IDs](https://wowpedia.fandom.com/wiki/UnitId), and player names are only valid Unit IDs if they are in your party or raid. I believe the only time it would work is if someone in your party or raid gets Mind Controlled.

**Comment by XyzKangUI** [comment]
Rip this ticket aswell.
