### ISSUE TITLE
[BUG] Majestic Dragon Figurine & Illustration of the Dragon Soul

### ISSUE THREAD

**Issue by NatsumeLily** [JamminL/wotlk-classic-bugs#517]
#### 1.1. Description
I haven't tested everything except for Wild Growth, Hurricane, Moonfire. 
Wild growth only gives 1 stack, Hurricane is 1 stack per tick, Moonfire is 1 stack in total. 
#### 2.1. Description
Here is the general rules for how it should work. 

Direct damage spells should give 1 stack and direct damage spells with additional DoT components should in addition give 1 stack per DoT tick.
DoTs should give 1 stack on application and 1 stack for every tick.
HoTs should give 1 stack on application and 1 stack for every tick.
Aoes should give 1 stack for every target hit.
Bleeds should not give any stacks.
Channeled spells should give 1 stack for every tick/hit.
Some random spells should also give 1 stack but it's case by case basis. (Levitate and Slow fall I know of)

**Comment by caccavale** [comment]
Can you source expected behavior for this?  Videos from retail?

**Comment by caccavale** [comment]
Cursory google search showing 3.0.8 changing it to not proc from periodic damage/heals without an instant component.
https://www.mmo-champion.com/threads/632184-Illustration-of-the-Dragon-Soul-or-quot-how-do-i-nerf-something-to-oblivion-quot

Expected behavior would be direct heal/damage spells proc 1 stack including some weird things like life tap.
DoTs, HoTs, channeled AoEs without an explicitly mentioned initial damage tick (e.g. hurricane) should not proc it.
