### ISSUE TITLE
[#SomeChanges Suggestion] Complete Elimination of AoE Aura Batching (Aura lingering)

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#53]
### Description
On behalf of everyone, we plead that similarly to spell batching (even more so in this case), aoe aura spell batching also gets heavily reduced or removed.

While spellbatching created some nice interactions that people loved, AoE aura batching does nothing except make the game look laggy and/or broken. Mechanics like this were probably added due to networking issues, they have been long forgotten by players who have devoted countless hours passionately to retail and pservers.

When you leave an AOE range, you expect the aura to fall off the moment you leave the AOE, not to have to wait for an inconsistent server tick to remove it.

This is some **wotlk beta** examples: 

https://gyazo.com/22e738bbe8789f99a247c5300e5a4374 Notice how long does it take for the rogue's flare debuff to be removed after leaving flare.

https://gyazo.com/0ccb275da80f78d45d9fc614cfb73b0c Notice how long does it take for the rogue's grounding totem to be removed upon leaving grounding totem range. And how long does it take to reapply once in range

This is far beyond expectations of what's written in tooltips or how spells are understood by the playerbase. We no longer need the dated systems that functioned well a few decades ago on older architecture, whereby the only explanation we can give in the present is "flare sometimes will have a 100+ yd range"

#RantOver 🐰

**Comment by Aggrend** [comment]
Thanks for the detailed suggestion here. We like this and agree in principle, and we've discussed this at length internally, but at this time we are not going to be making any changes here just due to the risk changes to this system could pose, as this could have a large impact on server performance.

As an aside to this, and this is potentially something that you already know; the main issue described here isn't so much "AoE batching" as much as it is "Aura Update frequency during movement". Movement is something that causes aura updates to be sent down from the server, and when you move consistently in a straight line, you don't get those updates instantly. A good workaround for this is to do a split-second strafe while moving forward out of an aura such as flare, as this will force a movement update, which will also force an aura update on the server. 

We agree its pretty weird, but this is ultimately just how the game works. One way to look at this is that it actually raises the skillcap if you can make use of movement updates to force aura updates at specific times. Regardless, great suggestion. Thanks!

**Comment by JamminL** [comment]
I appreciate the response, but if I may a slight correction:

It is true that in these videos they are walking straight which is adding to the problem. besides aura batching you have to take into account movement updates, but aura batch on its own is a problem.

Even if the clip was done with a player zig-zagging, it'd still take quite a long time for an aura to be removed.

**Comment by JamminL** [comment]
Closing for now though :'(

**Comment by Evolvee** [comment]
Maybe I am missing something but we tried all possible workarounds during classic TBC to make the flare debuff disappear faster, **nothing worked**, not even forcing the client to send movement packets to the server quicker than the default 0.5 sec (i believe thats the client update frequency when not changing direction?, or atleats thats the 2.4.3 client one, dunno if anyone reverse-engineered the classic one yet)

**Comment by perpabc** [comment]
> 

Agree with this; I advocated for movement updating to avoid things like fear, traps etc if you knew when to update your position, but it's not working as intended then because even through forcing a tick by strafing, you cannot trigger flare debuff to drop, or get the grounding effect when you should (re the clips above) 

Could you take a look at the reference client for this please? Moving while outside of flare to force the aura to update
