### ISSUE TITLE
[BUG] Corpse Explosion low range

### ISSUE THREAD

**Issue by JustForYou24** [JamminL/wotlk-classic-bugs#544]
#### 1.1. Description
Corpse Explosion range in description is 10m(15m with glyph), but really only melee range both with/without glyph/
  #### 1.2. How to Reproduce
          Just find dk and ask him to explode you. Its super obvious
  #### 1.3  Source Material
I think no need for that, because everything about range is written in decription/
#### 2.1. Description
It shoul be 10m range and 15 with glyph.
  #### 2.2 Source Material
no need.

**Comment by Miyur1** [comment]
NAB.
When it explodes, the ghoul uses another spell. This spell has a 5 yard radius 
https://www.wowhead.com/wotlk/spell=47496/explode

https://web.archive.org/web/20090301132247/http://www.arenajunkies.com/showthread.php?t=65627&page=2
- it has a very, very, very small radius
a lot smaller than 10 yards, very hard to use, even after a gnaw 

- ya i used it before they buffed it. The radius is TINY, if you dont have a snare on the enemy they can still move out of the blast radius even after a gnaw. 

http://web.archive.org/web/20150916084046/http://www.arenajunkies.com/topic/148625-corpse-explosion/page__st__40
- Its pretty simple, I can glyph it to a 15 yard range and itll miss 2 yards away from my opponent, waste my pet, waste my runic power, and open me up to a swap 

https://www.warcraftmovies.com/movieview.php?id=103989
1:58 Ghoul explodes, but misses neighboring dummies, which are located 8 yards from others

https://www.youtube.com/watch?v=h3UXFdwc04s&t=17s
Similar situation

Also, the glyph should not affect the ghoul's explosion:
https://web.archive.org/web/20130113203037/http://elitistjerks.com/f72/t42499-boom_corpse_explosion_thread/
Glyph: Does not work with Ghoul explode, works occasionally with Corpse explode. 

http://web.archive.org/web/20150916084046/http://www.arenajunkies.com/topic/148625-corpse-explosion/page__st__40
- CE glyph doesn't work on ghoul CE, since the ghoul's version is different from the actual corpse explosion spell.

- the glyph only affects corpses (dead things in arena) you explode and not your pets explosion radius
