### ISSUE TITLE
[BUG] Target maker disappears when casting Shadowmeld.

### ISSUE THREAD

**Issue by ahhiit** [JamminL/wotlk-classic-bugs#565]
#### 1.1. Description
Target maker disappears when casting Shadowmeld.
 
 #### 1.2. How to Reproduce
           1. raid or party and set target maker for Night Elf
           2. cast Shadowmeld
           3. Night elf target maker disappeared
 
 #### 1.3  Source Material
https://www.youtube.com/watch?v=Vf8odDyR5Ks

[###]()) 2. Expected Behavior
  #### 2.1. Description
           1. raid or party and set target maker for Night Elf
           2. cast Shadowmeld
           3. Night elf target maker disappeared
 
 #### 2.2 Source Material
https://www.youtube.com/watch?v=Vf8odDyR5Ks

**Comment by ManneN1** [comment]
It's been like this since as long as I can remember (at least since MoP/WoD, not sure if it was a thing in 3.3.5). 

It's so minor, just use an automarker WA to re-mark automatically. Or use this as your Shadowmeld macro:
/use Shadowmeld
/run C_Timer.After(2, function() if (GetRaidTargetIndex("player") ~= **symbol**) then SetRaidTarget("player", **symbol**) end end)

Replace **symbol** with 1-8 depending on which mark you want.
