### ISSUE TITLE
[BUG] DK - Summon Ebon Gargoyle does melee damage instead of casting as the tooltip mention

### ISSUE THREAD

**Issue by Stuffemcv** [JamminL/wotlk-classic-bugs#574]
#### 1.1. Description

The tooltip for Summon Gargoyle is currently describing this :

A Gargoyle flies into the area and bombards the target with Nature damage modified by the Death Knight's attack power. Persists for 30 sec.

Currently, the Gargoyle spawns at the target, and when the hitbox is too big, or when it feels like it, it starts to do melee attacks instead of casting the nature damage as the tooltips describes. This is inconsistent with the tooltip, and happens randomly :

#### 1.2. How to Reproduce

           1. Summon ebon gargoyle
           2. First hit is almost always a melee hit
           3. Thearfeter, depending on the boss, positioning of the gargoyle it will either start casting or melee

 #### 1.3  Source Material

https://classic.warcraftlogs.com/reports/c42HFrQpR8Ynk1gL#fight=2&type=damage-done&source=64
https://classic.warcraftlogs.com/reports/c42HFrQpR8Ynk1gL#type=damage-done&source=30&ability=-49206&fight=18
https://classic.warcraftlogs.com/reports/c42HFrQpR8Ynk1gL#type=damage-done&source=30&ability=-49206&fight=41

#### 2.1. Description

The gargoyle should be casting nature damage only, and do absolutely no melee attacks.

  #### 2.2 Source Material

![image](https://user-images.githubusercontent.com/122474409/211873683-d347ba8f-d9df-4cc2-9c7b-088f4f67bb14.png)

**Comment by Bakurersu** [comment]
Gargoyle did melee it's target sometimes in retail wrath when spawned in melee range, although if you have evidence to show otherwise it would be great to see it. The reason it melees so often in classic compared to retail wrath is because it's spawn behaviour is currently incorrect, instead of spawning at the front left of the direction the player is facing (which is how it spawned in retail wrath and early classic beta), it spawns directly above the centre of the target and then flies straight down before attacking. This means you cannot currently force the gargoyle to spawn out of melee range of the target, resulting in more common melee attacks as described in #386

**Comment by Stuffemcv** [comment]
Agreed, but this behaviour still doesn't match the tooltip even if OG wrath it was the case. Especially with the current nerf proposed, Gary should at least become consistent, especially as the current spawn mechanism really makes Gary melee more than 50% of the time in ulduar (hit box of bosses are ridiculously huge in Ulduar).
