### ISSUE TITLE
[BUG] DK Army of the Dead pre-pull not attacking consistently

### ISSUE THREAD

**Issue by lime-green** [JamminL/wotlk-classic-bugs#575]
#### 1.1. Description
Frost DKs can use Army of the Dead before the boss is pulled for a DPS gain. However, a lot of the time the ghouls don't start attacking for a while
  #### 1.2. How to Reproduce
           1. Cast army of the dead before a boss pull
           2. Notice how they can sometimes take a long time to start attacking, or even not attack at all
  #### 1.3  Source Material
  For example in this KT fight he engages the boss around 1:21:24 and the ghouls only start attacking at 1:21:44 (20s later) https://www.twitch.tv/videos/1680200747?t=1h21m16s
#### 2.1. Description
  Ghouls should start attacking your target immediately
  #### 2.2 Source Material
https://www.youtube.com/watch?v=v4mA3PyBBRE (from @danniellos94)

**Comment by danniellos94** [comment]
https://www.youtube.com/watch?v=v4mA3PyBBRE

**Comment by danniellos94** [comment]
https://www.youtube.com/watch?v=v4mA3PyBBRE before combat - precasting army
https://youtu.be/i7RRazukPq4?t=334 in combat casted army

**Comment by MHMabrito** [comment]
Do you have /petattack bound?

**Comment by lime-green** [comment]
@MHMabrito no because unfortunately that doesn't work as Frost since we don't have any pets so it doesn't do anything to help get army attacking

**Comment by Serenityrzx** [comment]
> Do you have /petattack bound?

No form of petstay / follow / defensive etc works with army of the dead.

**Comment by enthozzz** [comment]
This has been a bug since the start of classic. The only way to get them to attack seems to be bosses with hidden offensive mechanics that affect every creature like Patchwerk, summoning your lone ghoul once *in combat*, and using items/trinkets like Pumpkin Sword and Barov Peasant Caller. Forcing frost DK's to use items like these or lose alot of uptime by waiting until ~12 seconds into their opener when they should be summoning their lone ghoul is a heavy DPS loss and headache.
I would be more than happy to post numerous vods/clips of this behavior if needed.

**Comment by lime-green** [comment]
This is fixed

**Comment by lime-green** [comment]
Blue post here: https://us.forums.blizzard.com/en/wow/t/wrath-of-the-lich-king-classic-hotfixes-updated-february-8/1500326/81

<3 thanks team
