### ISSUE TITLE
[BUG] cleave or kologarn hit box is not the same

### ISSUE THREAD

**Issue by knasen88** [JamminL/wotlk-classic-bugs#596]
#### 1.1. Description
Cleaving main body hits no additional targets currently 
  #### 1.2. How to Reproduce
          Press cleave. Cry.

#### 2.1. Description
Clearly it should it all the targets in range. Might be similar story on mimiron aswell as cleave only hits middle and bottom will investigate later 
  #### 2.2 Source Material
https://youtu.be/7Fth40NcyOE the green flash on hands is a dead giveaway of cleave working

**Comment by danniellos94** [comment]
Can confirm same for heartstrike and it should work :
https://www.youtube.com/watch?v=PjOTW7CFBV4

**Comment by Xevaris** [comment]
I have attempted this on 10 man and 25 man versions and can confirm that cleave is not hitting any 2nd or 3rd targets if using Glyph of Cleaving

- 10 Man WCL Target Kologarn Only: https://classic.warcraftlogs.com/reports/W7yYwX9Vg6fhb1cm#fight=18&type=damage-done&source=3&ability=47520

During this attempt I only main targeted Kologarn and attempted to cleave off as much as possible. No cleaves were hitting Left or Right Arm.

- 10 Man WCL Target Arms: https://classic.warcraftlogs.com/reports/RpNk8yFwQdxY9P3A#fight=20&type=damage-done&source=4&ability=47520

This attempt I targeted right and left arms and attempted to cleave off to the main target, or other arms. Cleave still does not go to any other targets.

- 25 Man WCL Target Kologarn Only: https://classic.warcraftlogs.com/reports/fcrDTmAJZnRXqGx1#fight=19&type=damage-done&source=28&ability=47520

Same as the first 10 man attempt where I only attempted to cleave off Kologarn. Cleave does not hit any other targets.

- 25 Man WCL Target Arms: https://classic.warcraftlogs.com/reports/LznpFmDc6avJZV8j#fight=13&type=damage-done&source=11&ability=47520

Same as the 2nd 10 man attempt log. Here I attempted to hit the arms and cleave off but cleave does not hit any target other than main target.

I can also confirm that this bug was present on PTR: https://classic.warcraftlogs.com/reports/dgbJjW9cCHrm3txV/#fight=6&type=damage-done&source=24&ability=47520

**Comment by Xevaris** [comment]
Was able to utilize cleave to hit all three targets on my 25 man attempt this week. The position needed to execute this is essentially off the edge of the cliff in front of Kologarn.

Logs: https://classic.warcraftlogs.com/reports/1cLBMqNmVt974zwg#fight=26&type=damage-done&source=23&ability=47520

**Comment by knasen88** [comment]
i too have found it but it's a bit ridiculous you gotta step into a pixel wide spot to reach it when every other aoe works fine.
