### ISSUE TITLE
[BUG] DPS Warrior T8 4-set bonus crit chance is lower than expected

### ISSUE THREAD

**Issue by TheGroxEmpire** [JamminL/wotlk-classic-bugs#611]
#### 1.1. Description
DPS Warrior T8 (Siegebreaker Battlegear) 4-set that supposedly should give extra 10% crit chance to Bloodthirst and Mortal Strike is instead giving 4-5% crit chance on dummy test.
However, when we looked at the 4-set bonus tooltip on Wowhead, it has a hidden 40% proc chance (https://www.wowhead.com/wotlk/spell=64939/item-warrior-t8-melee-4p-bonus). This 40% proc chance is the same as the T8 2-set (https://www.wowhead.com/wotlk/spell=64938/item-warrior-t8-melee-2p-bonus).
  #### 1.2. How to Reproduce
          1. Equip 4-set of T8 DPS warrior piece.
          2. Do a prolonged hits of Bloodthirst / Mortal Strike.
          3. Observe that the crit chance is lower than expected.

  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/47816228/218257162-6da8ac52-8de5-44c1-a551-059df4d26d83.png)
Left side: without 4-set. Right side: with 4-set

486 Bloodthirst casts without 4-set:
![image](https://user-images.githubusercontent.com/47816228/218257238-c9fa67ac-8a18-450c-a35d-95c0fb416f8f.png)
(https://classic.warcraftlogs.com/reports/AWR2hQ7qvrTFj63f/#fight=3&type=damage-done&source=6)

456 Bloodthirst casts with 4-set:
![image](https://user-images.githubusercontent.com/47816228/218257297-a73dbe94-8f4a-48a5-b636-c56fc3ca57c5.png)
(https://classic.warcraftlogs.com/reports/AWR2hQ7qvrTFj63f/#fight=4&type=damage-done&source=6)

Credit to indyssd#9843 for providing with testing data.

#### 2.1. Description
It wouldn't make sense to have 4-set tooltip saying that it would grant flat 10% Bloodthirst / Mortal Strike crit chance and having a hidden proc chance behind it. If this was indeed the case, then the tooltip should have been corrected to 4% extra Bloodthirst / Mortal Strike crit chance.

**Comment by TheGroxEmpire** [comment]
As another comparisson, the tank 2-set bonus doesn't have the same issue as the other set bonus (4-set) doesn't have proc chance on it.
![image](https://user-images.githubusercontent.com/47816228/218258450-24d2bbaa-da21-49e0-a5ae-e90f9348ebe6.png)

**Comment by Aggrend** [comment]
Going to post a lot of words, but TLDR; This isn't a bug. 

There's a few things going on here, some of it is bad (but authentic) 3.3.5 data, some of it is some flaws in how this was tested above.

Regarding the 40% "proc chance" this does not affect this set bonus at all. When this set bonus was originally created in 2008, the designer who made it copied the 2pc set bonus data record and implemented the 4pc bonus on that newly copied data record, but forgot to delete the proc chance from the spell data. However, the proc effect on the 4pc bonus record points to **nothing** and is effectively junk data that has no functionality at all. The presence of this junk data is definitely a bug, but is benign and has no impact on function of the 4 set bonus at all. The designer who did this is still at the company and confirmed this with us.

Next, there's some flaws in the data presented in the bug report above. Namely, the first dataset without the set bonus was done against the Grandmaster's Training Dummy which is level 80. The next dataset with the set bonus showing a lower-than-expected crit rate is against the Heroic Training Dummy which is a level 83 (??) boss level mob. Having a lower crit rate than is displayed on your character sheet is expected against raid bosses.

To fully put this to bed, we did some internal tests using a character with a static 90% chance to crit and the 4pc bonus and here's what we saw against the level 80 dummy:
![image](https://user-images.githubusercontent.com/81382721/218853199-510c5126-d51a-4f2b-b44a-ecd0704494be.png)


Next, here's another dataset on the same target WITHOUT the 4pc set:
![image](https://user-images.githubusercontent.com/81382721/218853106-ad40229c-11f2-4278-af8b-7d2a349a9eac.png)

Finally, here's a dataset with the 90% crit character using the 4pc bonus against the heroic (level 83) dummy. Note the reduction in crit rate due to the level disparity:
![image](https://user-images.githubusercontent.com/81382721/218853486-2593d260-3140-4693-8371-d884939399e8.png)

In summation, this crit reduction against raid bosses is perfectly expected behavior and when you combine the confusing, unused proc data with inconsistent variables used for this test, you can quickly see how someone could have arrived at the conclusion that something was wrong. 

We'll look into potentially removing the bad proc data so it's less confusing, but all told, the 4pc works as expected. 

Thanks for the report! In the future I'd suggest being extra sure you are isolating variables and using identical targets for each of your datasets for better consistency.
