### ISSUE TITLE
[BUG] Judgment of the Just and recent changes

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#659]
#### 1.1. Description
Judgment of the Just with Judgment triggers stacks of Seal of Vengeance. The bug most likely appeared after buffs paladins.
  #### 1.2. How to Reproduce
           1. Learn Judgment of the Just
           2. Press Judgment
  #### 1.3  Source Material
https://www.youtube.com/watch?v=AJsV_Qx5mxs
#### 2.1. Description
Judgment of the Just should not trigger stacks of Seal of Vengeance/Corruption. According to [this](https://us.forums.blizzard.com/en/wow/t/upcoming-adjustments-to-retribution-paladins/1511714/1) post, the changes should only apply to "Divine Storm" and "Crusader Strike". 
  #### 2.2 Source Material

In these timecodes you can see how Judgment with Judgment of the Just does not trigger stacks of Seal of Vengeance/Corruption	
https://www.youtube.com/watch?v=nBxgUDO2xnA&t=15s
https://www.warcraftmovies.com/movieview.php?id=155093 @ 1:18
https://www.warcraftmovies.com/movieview.php?id=159747 @ 6:12

**Comment by Undertoe** [comment]
This is 99% NAB as it is in line with various other mechanics:

1) JOTJ has always caused seal of the righteousness to proc a tick, which means its flagged as a melee attack
2) SOV has been changed as of the glyph of reckoning change to proc off of a variety of different effects and increment stacks off of them (CS / DS / HOW naming a few).
3) Since JOTJ has always counted as a melee attack, it causing SOV to increment is going to be exactly in line with current effects.

**Comment by Undertoe** [comment]
A final note is that SOV damage has always "procced" from judgements when JOTJ has been specked, its just now its also incrementing stacks, which is again, in line with mechanics of all other spells.

This is also in line with the holy paladin Judgements of the Pure talent (I believe)
