### ISSUE TITLE
[BUG] Hunter Feign Death triggering Combat incorrectly

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#68]
#### 1.1. Description
In PVP, if a hunter /petattacks someone and then presses feign death, the hunter gains combat even though neither the pet or the hunter are in combat.
  #### 1.2. How to Reproduce
           1. Command your pet to attack a player
           2.  Press Feign death (before or after pet starts attacking, doesn't matter and the result is the same)
           3. Check you gained combat
  #### 1.3  Source Material
https://gyazo.com/35394afd8539ce87e98012f7072aff26

#### 2.1. Description
In PVP, pets dont give combat to owners, unless the owners buff them. This behavior is correct and intended. (They do however keep combat, but that's another story and also correct atm on beta)

So even if you feign death while a pet is /petattacking something, you should not magically gain combat. especially if the pet isn't in combat either.

  #### 2.2 Source Material

**Comment by leekzy** [comment]
Adding invisibility to this, also currently gives you combat when sending Water Elemental to attack and has during all of TBC.

Video:
https://streamable.com/2u6ebq

How to reproduce:
1. Summon Water Elemental
2. Send Water Elemental to attack target, can be any range (wele doesn't have to hit something/get combat for this to work)
3. Use Invisibility
4. Be granted combat status upon entering invisibility

This leads to mage and/or hunter team being able to avoid every rogue opener in 3s and 5s arena, extra brutal early seasons

**Comment by Evolvee** [comment]
Due to debuffs not being removed when entering arena, you can also trade combat before the gates even open by casting paladin´s sacrifice on a partner with a dot, getting dmg from it and entering combat (even when your partner is not in combat)... for some reason.

Another exploit is that when you enter arena, pets arent removed and instead they are summoned in in a combat state (if you were in a combat with them prior to entering arena), all it requires is you to buff your pet and voilà..

Ppl have been exploiting these since day 1 of TBC and nothing was done about it despite it being reported quite frequently.

**Comment by Aggrend** [comment]
Going to call this NAB for now. As presented above, this behavior matches 3.3.5.
