### ISSUE TITLE
[BUG] Glyph of Quick Decay reduces Corruption ticks

### ISSUE THREAD

**Issue by Zephancode** [JamminL/wotlk-classic-bugs#73]
## 1. Describe the bug
[Glyph of Quick Decay](https://www.wowhead.com/wotlk/item=50077/glyph-of-quick-decay) should reduce the time between corruption ticks based on your haste (and other cast speed modifers). In the current build it only reduces the duration when corruption is refreshed through everlasting affliction and not on the initial application. 

During retail you lost a tick on when corruption was refreshed through everlating affliction whenever it would run out. This phenomenon could be called "backloaded clipping", and is further described in the [comment from Wallirik](https://github.com/JamminL/wotlk-classic-bugs/issues/73#issuecomment-1169456836). What currently happens is that you lose out on more than this "backloaded" tick.

### 1.1 To Reproduce
1. Talent into Everlasting Affliction and Glyph Quick Decay
2. Gain any cast speed increase
3. Cast Corruption -> 6 ticks / 3 seconds between ticks? 
4. Refresh Corruption through Everlasting Affliction -> count remaining ticks/time between ticks

### 1.2 Source Material
- [Retail dual showing "backloaded clipping" causing **5 ticks**.](https://youtu.be/ftDakv_-DwQ?t=207)
- On beta showing corruption gets removed after **4 ticks**(with remaining duration on the debuff).
- [Beta Warcraft log showing initial corruption doesn't benefit from the glyph.
](https://gyazo.com/aab40deb1712dd47bebbc4e229e49e75)
3.4.0 Build 44301

## 2. Expected behavior
Glyph of Quick Decay should shorten the duration of Corruption based on the cast speed % increase, but only lose out on a single tick when corruption runs out.

### 2.1 Source expected behavior
https://youtu.be/ftDakv_-DwQ?t=207
This clip illustrates the "lost tick" from a drain life refresh. Eradication buff is up for this corruption.

    Warlock casts drain life to refresh corruption and fake CS - as this happens the UA ticks for 1138.
    Corruption has been refreshed, and now sits a full duration on the mage, it was refreshed approximately 0.5 seconds before it would've ticked.
    Just after the UA tick for 1138, corruption ticks for 1370, keep counting and you can see 1 more tick for 1370 followed by 3 absorbs - resulting in 5 ticks total (clipped 1 tick short at the end because dot ends before tick happens)
    Notice though, how corruption just drops abruptly on the last tick instead of lingering without ticking at the end.

### 2.2 Additional context

Edit: added further context and adjusted based on feedback from Wallirik

**Comment by Wallirik** [comment]
I don't think 5 ticks of corruption proves that there is some bugged interaction here.

I have visualized my thoughts on how i think it should work in this paint picture https://i.imgur.com/4iXgxm8.png
The first bar is a manual application of a 0% haste corruption 18 sec duration ticking every 3 seconds - 6 ticks

The second bar is a hasted 12second duration dot with a tick time of 2seconds (i think that's correct?)
The second bar shows a everlasting affliction refresh just after the dot has ticked, just barely missing the 6th tick as the dot expires, resulting in only 5 ticks after drain life was casted (or haunt, or shadow bolt, should be the same thing).

You could call this lost tick 'backloaded clipping', as you will only ever lose a tick of corruption if you actually let the dot run its full duration - if you are just dps'ing a boss or whatnot you will never lose a tick.

https://youtu.be/ftDakv_-DwQ?t=207
This clip illustrates the "lost tick" from a drain life refresh. Eradication buff is up for this corruption.
1. Warlock casts drain life to refresh corruption and fake CS - as this happens the UA ticks for 1138.
2. Corruption has been refreshed, and now sits a full duration on the mage, it was refreshed approximately 0.5 seconds before it would've ticked.
3. Just after the UA tick for 1138, corruption ticks for 1370, keep counting and you can see 1 more tick for 1370 followed by 3 absorbs - resulting in 5 ticks total (clipped 1 tick short at the end because dot ends before tick happens)
4. Notice though, how corruption just drops abruptly on the last tick instead of lingering without ticking at the end.

However, when trying to replicate this on a dummy with eradication proc, the corruption just abruptly ends after only 4 ticks (supposed 5?)
https://gyazo.com/aab40deb1712dd47bebbc4e229e49e75
(see ticks after haunt lands in combat log, the refresh of corruption - only 4 ticks)

Something is definitely off with 'everlasting affliction' and the 'glyph of quick decay'. But I'm not sure it's the 5 ticks that is broken.

It is definitely correct that the glyph doesn't work on the initial cast of corruption. As can be seen on this quite scuffed log from beta https://classic.warcraftlogs.com/reports/fB973RLYqdbp2KVm/#fight=last&type=damage-done&view=events&options=2 

Corruption is cast at 24 seconds and ticks at 27, 30, 31 haunt lands, 33 tick again - and now the haste takes effect as corruption ticks at 35-37-39 (again resulting in only 4 ticks after haunt lands)

**Comment by Zephancode** [comment]
@Wallirik Thank you for the detailed description and evidence. 

Seems that 'backloaded clipping' indeed was a thing based on that video, and it likely isn't widely talked about because in most circumstances where you keep corruption up through everlasting affliction you don't let it run out either. 

I'll add your evidence to the post above and reframe it to make the actual current bug clear: Quick Decay doesn't work on the initial application and causes corruption to drop too soon (aside from 'backloaded clipping').

**Comment by Tharre** [comment]
Still broken as of build 44930.

**Comment by watchyoursixx** [comment]
fixed at some point
![image](https://user-images.githubusercontent.com/47162044/194187671-79fc1c4d-34a9-4e82-8101-1acb2727c65e.png)

Ticks properly get hasted, and refreshing with a close to instant tick as possible, I get 6 ticks each time.

Note: this has similar effects as serpent sting refreshed from chimera, or some other talents/abilities that refresh dots. They do NOT lose ticks, but the duration can "change" based on the time of refreshing. The interval between ticks stays consistent. So a dot refreshed .1s before the next tick will have tick #1 at 0.1 seconds, instead of 3 or whatever the tick rate is. This ends up making the duration "2.9s" shorter, but still provides same # of ticks.
