### ISSUE TITLE
[BUG] Deathknight t10 4p is not visibly proccing

### ISSUE THREAD

**Issue by lime-green** [JamminL/wotlk-classic-bugs#783]
#### 1.2. How to Reproduce
           1. Put all runes on CD 
           2. See no Advantage buff is given
  #### 1.3  Source Material
From @osijek031, see buff is not proccing https://youtu.be/ElhhVuH3g5Q
#### 2.1. A damage buff should be shown
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
https://www.youtube.com/watch?v=RIZn8ZYhU70
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/9436142/f63ff2f6-122e-4385-8c3a-d26341895e7c)

**Comment by osijek031** [comment]
1. Current Behavior
1.1. The 4p should proc a 3% damage buff when all runes are on CD (https://www.wowhead.com/wotlk/spell=70657/advantage)
1.2. How to Reproduce
       1. Put all runes on CD 
       2. See no Advantage buff is given
1.3 Source Material
2. Expected Behavior
2.1. A damage buff should be shown
{Describe how that mechanic/spell/npc should be working, in detail}

Once you use all your runes on CD you should be getting a buff aura that gives you 3% damage increase for 15 sec and it refreshes each time you dump all runes 

This is me trying to make it proc live on Golemagg realm 25.10.2023 - https://youtu.be/ElhhVuH3g5Q

**Comment by lime-green** [comment]
Hotfixed https://www.wowhead.com/wotlk/news/hotfixes-october-25-wotlk-classic-335722
