### ISSUE TITLE
[BUG] Dodge Chance attacking from Behind

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#9]
### Description
If the target is in-front of you with his back facing you, but somewhat close then your spells and attacks will still have a chance to dodge. 

This should be incorrect behavior.

If you're attacking an enemy while his back faces you, then your spells and attacks shouldn't dodge.

Classic TBC current behavior (same thing happens in wotlk classic)
https://streamable.com/s93vn0

**Comment by watchyoursixx** [comment]
this has been open a while, but I "believe" that it's technically NAB.

Players and units have a base hitbox of I believe 2.166 yds that is "centered" meaning that attacking a target within this "center" is considered attacking from the front. That's why technically when melee dpsing, you don't ever want to stand *inside* the boss, but rather at a minimum slightly towards the outer circle or their feet. If I recall correctly at some point this was confirmed to be correct, either in vanilla or TBC but it's been so long I can't remember exactly. Whether this affected pvp in wotlk specifically I'm not sure.

Something interesting to test would be if gouge also works in this area, or if it recognizes that you are actually behind the target but still uses the same hit tables as if attacking from the front. I'd expect if you attacked a shielded tank player you would similarly see parry and blocks from behind.

**Comment by Miyur1** [comment]
NAB
https://www.warcraftmovies.com/movieview.php?id=136127 @ 29:40
https://youtu.be/ldFJfXwmp-E?t=289

**Comment by JamminL** [comment]
While I don't think those are the best examples, I'll still mark it as NAB because it most likely is.

I hate it and I hate that you can backstab and dodge at the same time but here we are
